### ISSUE TITLE
how to unsubscribe from ws client

### ISSUE THREAD

**Issue by junminstorage** [enisdenjo/graphql-ws#101]
### Story

per https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#streaming-operation,  it looks like ws client can unsubscribe from server, so the stream can be stopped. 

also ubscriptions-transport-ws has a dedicated interface to do so by sending messageType.STOP to server: https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/message-types.ts#L14 

### Acceptance criteria

- Provide sample working code to demonstrate how to do so.

**Comment by enisdenjo** [comment]
What you are looking for is [the Complete message](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#complete).

Here it is in the `MessageType`:
https://github.com/enisdenjo/graphql-ws/blob/ae71a039c0a7f4a4dd60b2ca94c30b483ca8ebd7/src/message.ts#L25

**Comment by junminstorage** [comment]
Is there any method exposed from the client to do so?  e.g.
```
client = createClient()
id = client.subscribe()
client.unsubscribe(id) or client.sendMessage(messageType, payload) 
```
Let me know if my question or proposal above make sense.

**Comment by junminstorage** [comment]
Got it! Thanks. I read the client.ts again, the subscribe fn is a bit convoluted as we expect from JS code. now it makes sense. 
https://github.com/enisdenjo/graphql-ws/blob/ae71a039c0a7f4a4dd60b2ca94c30b483ca8ebd7/src/client.ts#L548

also you document the return fn here:
https://github.com/enisdenjo/graphql-ws/blob/ae71a039c0a7f4a4dd60b2ca94c30b483ca8ebd7/src/client.ts#L168-L170
