### ISSUE TITLE
[Question or Bug] resolving subscription queries doesn't work when using a resolvers map 

### ISSUE THREAD

**Issue by Momics** [enisdenjo/graphql-ws#106]
**Expected Behaviour**
I expected my subscription resolver 'person' to resolve correctly from the resolvers attached to the schema, either with or without specifying it inside the 'roots' server option.

**Actual Behaviour**
but instead it seems to only resolve correctly when adding subscription resolvers to the roots variable and removing the subscription type from the resolvers map.

**Debug Information**
I'm not sure if this is intended behaviour but I am getting different results based on whether I add the 'Subscription' root type to the resolver map yes/no.

1. With the subscription resolver added to the resolvers map and to the roots option, the 'person' field resolves to an AsyncIterator.
2. With the subscription resolver added only to the resolvers map and leaving the roots option of the server undefined, it is not resolved at all
3. With the subscription resolver removed from the resolvers map and added to just the roots option of the server, everything is working as expected. 

I've added my code below. I am coming from Apollo Server which does a lot of work behind the scenes, so this might just be an ignorant question and not a bug...

```ts
import { addResolversToSchema } from "@graphql-tools/schema";
import { buildSchema, execute, subscribe } from "graphql";
import { useServer } from "graphql-ws/lib/use/ws";
import http from "http";
import ws from "ws"; // yarn add ws

const server = http.createServer(function weServeSocketsOnly(_, res) {
  res.writeHead(404);
  res.end();
});

const wsServer = new ws.Server({
  server,
  path: "/graphql",
});

const schema = buildSchema(`
  type Query {
    _empty: String
  }

  type Subscription {
    person: Person!
  }

  type Person {
    name: String!
    age: Int!
  }
`);

const resolvers = {
  Person: {
    age(ctx, args, root) {
      return ctx.age + 5;
    },
  },

  Subscription: {
    person: async function* personName() {
      
      for (const name of ["Patrick", "Henk", "Angela", "Steve"]) {
        yield { person: { name, age: 5 } };
      }

    },
  },
}

// I setup the roots option here and later remove the root query types from the resolvers map
// otherwise my 'person' resolver doesnt resolve correctly.
const roots = {
  subscription: resolvers.Subscription,
}
delete resolvers.Subscription;

const schemaWithResolvers = addResolversToSchema({
  schema,
  resolvers,
});

useServer(
  {
    schema: schemaWithResolvers, // from the previous step
    roots,
    execute,
    subscribe,
  },
  wsServer
);

server.listen(8080, () => {
  console.log("Listening");
});
```

**Comment by enisdenjo** [comment]
Hmm, I am not sure what is happening here. Are you sure its this library causing the issue? The code for subscribing on the server is ultra simple, I just organise the values and use `graphql`'s `validate`, `execute` or `subscribe` functions:
https://github.com/enisdenjo/graphql-ws/blob/c667d704f5be20377cb7f09e5f62dd5d27fcdd3f/src/server.ts#L611-L658
If you're confident its `graphql-ws` thats the culprit, a repro (or a failing test) would be awesome.

**Comment by Momics** [comment]
I investigated a little further and found that using the following style of resolver fixes the issue:

```ts
export const resolvers = {
  Subscription: {
    test: {
      resolve: (payload) => payload,
      subscribe: personName
    },
  },
};

async function* personName() {
  for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
    yield { name: hi, age: 2 };
  }
}
```

With this setup everything is working as expected. Not sure why though, but this solves my problem.
