### ISSUE TITLE
Missing closed event when calling client.dispose

### ISSUE THREAD

**Issue by asmeikal** [enisdenjo/graphql-ws#108]
**Expected Behaviour**
As described in #105 , I'd expect the client to emit the `closed` event when manually calling the `dispose` method.

**Actual Behaviour**
No `closed` event is dispatched.

**Debug Information**
This test (added to `tests/client.ts`) highlights the problem:

```typescript
  it('should emit closed event when disposing', async (done) => {
    const { url } = await startTServer();

    const client = createClient({
      url,
      retryAttempts: 0,
      onNonLazyError: noop,
      on: {
        closed: () => {
          done();
        },
      },
    });

    const sub = tsubscribe(client, {
      query: 'query { getValue }',
    });

    await sub.waitForNext((result) => {
      expect(result).toEqual({ data: { getValue: 'value' } });
    });

    await client.dispose();
  });
```
The `onClose` method on the server is called, in this example.

**Further Information**
Strangely enough, replacing `await client.dispose()` with `await sub.waitForComplete()` works.

**Comment by enisdenjo** [comment]
Awesome! The problem was that I reset the emitter before the socket closes removing all listeners first. I've realised that there is no need to even reset it, so I've dropped it completely.

Added your test as well, shouldnt happen again.
