### ISSUE TITLE
Add connection_error to protocol

### ISSUE THREAD

**Issue by andyrichardson** [enisdenjo/graphql-ws#112]
### Story

Currently there is no way to send an error if a semantically invalid message is sent on `connection_init`.

It would be great if the protocol supported a `connection_error` message [similar to this](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md#gql_connection_error).

> Note: I'm aware of the existing error message - it requires a subscription ID which would not be present at `connection_init` time

### Acceptance criteria

- The protocol accommodates for errors on `connection_init`
- These errors do not have an `id` attribute

**Comment by michelepra** [comment]
what about #78 ???

**Comment by andyrichardson** [comment]
I was looking through the server side code and it looks like the current implementation closes on failure following `connection_init` - I'll go with that 👍

**Comment by enisdenjo** [comment]
Exactly as @michelepra suggested. The WebSocket close event is meant to communicate the connection close reason. You're free to pick [any user-land close code number within 4000-4999](https://tools.ietf.org/html/rfc6455#section-7.4.2) and whatever close reason string you like (or even a stringified JSON if you want to transfer more meaning). Use the client-side `error` or `on.disconnect` to act accordingly.

**Comment by lovasoa** [comment]
Hasura GraphQL uses a `connection_error` message:  https://github.com/enisdenjo/graphql-ws/issues/499

**Comment by enisdenjo** [comment]
This `connection_error` message type is OK in the [deprecated `subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws), but does not exist in the [GraphQL over WebSocket spec](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) and should not be used.

Also read https://github.com/enisdenjo/graphql-ws/issues/112#issuecomment-779950932.

**Comment by lovasoa** [comment]
But is is actually used in real applications that are deployed out there... Maybe it should be added to the PROTOCOL.md in this repo ?

**Comment by enisdenjo** [comment]
Mainly because [deprecated subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws) is still out there.

**Comment by enisdenjo** [comment]
As explained in https://github.com/enisdenjo/graphql-ws/issues/112#issuecomment-779950932, the `connection_error` message is superfluous and therefore completely unnecessary.
