### ISSUE TITLE
[client] "closed" event isn't triggered on socket disconnect

### ISSUE THREAD

**Issue by andyrichardson** [enisdenjo/graphql-ws#115]
# About

When a socket is disconnected, the "closed" event isn't emitted

# Reproduction

 - Pull [this reproduction](https://github.com/andyrichardson/graphql-ws-repro)
 - Change the URL in the `index.js` to a valid endpoint
 - Run `yarn start`
 - Open browser and open console
 - Disconnect device from the network

## Expected result

The following events are logged in the console:

 - `connecting`
 - `connected`
 - `closed`

## Actual result

The following events are logged in the console:

 - `connecting`
 - `connected`

(no closed event)

## Screenshot

![Kapture 2021-02-15 at 17 48 11](https://user-images.githubusercontent.com/10779424/107979211-13b08a80-6fb6-11eb-9cc5-cea2702982a7.gif)

> Note: This issue is not exclusive to simulating offline network states (e.g. disconnecting device from network also has same result)

**Debug Information**

See repro

**Comment by andyrichardson** [comment]
Closing as this is better encapsulated by #117

**Comment by michelepra** [comment]
Online/Offline switch in chrome devtool not affect websocket connection.

To simulate connection lost in client side:

- :scissors: network cable (:scream: please not do)
- disable network interface
- unplug network cable
- switch off wifi

If you have control of server

- stop application
- unplug network wire (virtual or phisical)

**Comment by enisdenjo** [comment]
As @michelepra said, the test case you provided is not valid. If you indeed think `closed` events are not dispatched, please do make a proper repro (or a failing test).
