### ISSUE TITLE
Package subpath './package.json' is not defined by "exports"

### ISSUE THREAD

**Issue by mlilja01** [enisdenjo/graphql-ws#118]
Hi,
as of 4.1.4 I can no longer build in OSX. I get the error 'Package subpath './package.json' is not defined by "exports" in node_modules/graphql-ws/package.json.

Adding this line to the "exports" section of the graphql-ws/package.json fix the issue, but I'm not sure if it is the correct way of fixing it.

```
...
"exports": {
  "./package.json": "./package.json",
  ".": {
....

```

**Comment by n1ru4l** [comment]
Sorry for breaking that! Yeah, that is missing and the correct way of exporting the package.json. See https://github.com/preactjs/preact/blob/b396932f6691d3bc05c9cf23e121e1c711790006/package.json#L12-L65 as a reference. I created https://github.com/enisdenjo/graphql-ws/pull/119 which should address this :)
