### ISSUE TITLE
preact cli fails on graphql-ws import

### ISSUE THREAD

**Issue by tot-ra** [enisdenjo/graphql-ws#140]
Hey. I use [preact](https://preactjs.com/) which apparently uses preact-cli and inside babel 
`preact watch --src app`

So when I import graphql-ws in frontend, build fails due to this line
```
 Build  [                    ] 0% (9.4s) compiling(62:20)       switch-case fall-through not supported - added break. See https://github.com/MatAtBread/nodent#differences-from-the-es7-specification
(88:20) switch-case fall-through not supported - added break. See https://github.com/MatAtBread/nodent#differences-from-the-es7-specification
(232:20)        switch-case fall-through not supported - added break. See https://github.com/MatAtBread/nodent#differences-from-the-es7-specification
Build failed!

✖ ERROR ../node_modules/graphql-ws/lib/server.mjs 133:22
Module parse failed: Unsyntactic break (133:22)
File was processed with these loaders:
 * ../node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|                       // @ts-expect-error: I can write
|                       ctx.acknowledged = true;
>                       break;
|                     } catch ($boundEx) {
|                       return $error($boundEx);
 @ ../node_modules/graphql-ws/lib/index.mjs 2:0-29 2:0-29
 @ ./components/api.js
 @ ./components/app.js
 @ ./index.js
 @ ../node_modules/preact-cli/lib/lib/entry.js
```

Its likely an issue of nodent how it interprets mjs source code.. but I don't have a way to change that

**Comment by enisdenjo** [comment]
Hmm, strange... All of my switch cases end with a `throw`, `return` or a `break`. No case falls through.

However, I've managed to replicate this build issue myself, the line numbers are off - might be that babel's transformation mess something up.

This is just a quick update, investigation is still ongoing.

**Comment by enisdenjo** [comment]
Yup, you were right, seems to be an issue with `nodent`. Check it out here: https://github.com/MatAtBread/nodent/issues/116.

**Comment by enisdenjo** [comment]
[Replacing the `break`s at case ends with `return`s](https://github.com/enisdenjo/graphql-ws/commit/e9447e45cfa572982e7fe0ffa32a113feac06b94) fixes the unsyntactic break. `nodent` still raises a warning, but the compilation succeeds.

[`graphql-ws@4.2.2`](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.2.2) now compiles with preact-cli.
