### ISSUE TITLE
socket.close fired but not 'onClose' callback from useServer

### ISSUE THREAD

**Issue by c4c1us** [enisdenjo/graphql-ws#152]
Hi,

I was trying to fire the `onClose` callback from `useServer` by closing my tab on Chrome. The function is never fired, but `socket.on("close",..)` is.

Is this a bug or a normal behaviour ?

```js
useServer(
    {
      onConnect: ctx => {

        ctx.extra.socket.on("close", o => {
          console.log(`REALLY CLOSED`);
        });

      return true;
     },
     onClose: () => {
        console.log("CLOSED BY SERVER");
      },
   }
```

**Comment by enisdenjo** [comment]
Hmm, the `onClose` should most definitely be called. I listen for the close the same way you listen for it in the `onConnect` example:
https://github.com/enisdenjo/graphql-ws/blob/c0b171e6fca65e0496aab70d3da84ac4c2917269/src/use/ws.ts#L107-L118

and then the `closed` call does:
https://github.com/enisdenjo/graphql-ws/blob/c0b171e6fca65e0496aab70d3da84ac4c2917269/src/server.ts#L731-L740

Could you share a simple repro? Maybe some of the cleanup actions stall.

**Comment by c4c1us** [comment]
Hum,

I think it's related to my async iterator on my subscription (I will share a repo if this still not help).

This code calls `onClose`:
```js
useServer(
    {
     ...
      schema,
      roots: {
        subscription: {
          async *allChannelEvent() {
            logger.info("allChannelEvent: ");

            try {
              for (const hi of ["Hi", "Bonjour", "Hola", "Ciao", "Zdravo"]) {
                yield {
                  allChannelEvent: {
                    channelId: "$ID",
                    type: "IS_TYPING",
                    userId: "$ID",
                    __typename: "ChannelEventResult"
                  }
                };
              }
            } catch (e) {
              console.log(`Error allChannelEvent: ${e}`);
            } finally {
              console.log("Finally allChannelEvent");
            }
          }
        }
     ...
  }
)
```

This code not fire 'onClose'
```js
useServer(
    {
     ...
      schema,
      roots: {
        subscription: {
          async *allChannelEvent() {
            logger.info("allChannelEvent: ");

            try {
              const iterator = pubsub.asyncIterator("$ID");

              let next;

              while ((next = await iterator.next()).done === false) {
                yield {
                  allChannelEvent: next.value
                };
              }
            } catch (e) {
              console.log(`Error allChannelEvent: ${e}`);
            } finally {
              console.log("Finally allChannelEvent");
            }
          }
        }
     ...
  }
)
```

The pubsub code is similar to this [repository](https://github.com/davidyaha/graphql-redis-subscriptions/tree/master/src).

**Comment by n1ru4l** [comment]
What version of graphql.js are you using?

**Comment by enisdenjo** [comment]
Can you check if the `while` loop breaks when `return`ing the iterable (you can just add a log statement below it)? My guess is that it gets stuck.

Also, why use the `while` loop instead of a `for async of` loop? Like this:
```ts
const iterator = pubsub.asyncIterator('$ID');

for await (const next of iterator) {
  yield {
    allChannelEvent: next.value,
  };
}
```

**Comment by enisdenjo** [comment]
Any news @c4c1us?

**Comment by c4c1us** [comment]
Hi,

I'm testing your code above.

**Comment by c4c1us** [comment]
Hi again,

@n1ru4l  Node v14.15.1 / GraphQL 14.5.8

@enisdenjo 
Still not working with the `for` loop, kind of stuck like you said. I faked an async iterator with a `setTimeout`and a got the same issue, the WebSocket won't close.

```
  function sleep(ms: number) {
    return new Promise(resolve => setTimeout(resolve, ms));
  }

  async function getAsyncData() {
    await sleep(15000); // simulate database/network delay...
    return [1, 2, 3, 4, 5]; // ...then return some data
  }

  const asyncIterable = {
    async *[Symbol.asyncIterator]() {
      yield* await getAsyncData();
    }
  };

useServer(
    {
     ...
      schema,
      roots: {
        subscription: {
          async *allChannelEvent() {
            logger.info("allChannelEvent: ");

            try {
              for await (const item of asyncIterable) {
                console.log(item)
                yield {
                  ...
                };
              }
            } catch (e) {
              console.log(`Error allChannelEvent: ${e}`);
            } finally {
              console.log("Finally allChannelEvent");
            }
          }
        }
     ...
  }
)
```

**Comment by n1ru4l** [comment]
might be related to this https://github.com/graphql/graphql-js/issues/2983 (Note: i dis not verify, just saw the issue and it seems this might be related)

**Comment by enisdenjo** [comment]
@c4c1us well, the for loop must break after returning the iterator for the teardown to work... As you mentioned in https://github.com/enisdenjo/graphql-ws/issues/152#issuecomment-816831180, if the loop breaks, `onClose` gets called; therefore - the bug is not related to `graphql-ws`.

**Comment by c4c1us** [comment]
@n1ru4l  I downgrade to 14.10.1, It didn't fix the issue.

@enisdenjo I change my subscription and put this :
```js
...
subscription: {
allChannelEvent: () => ({
            async return() {
              console.log("RETURN");
              await sleep(1000);
            },
            async throw() {
              console.log("THROW");
              await sleep(1000);
            },
            async *[Symbol.asyncIterator]() {
              const iterator = pubsub.asyncIterator(
                "$ID"
              );

              for await (const value of iterator) {
                yield {
                  allChannelEvent: value
                };
              }
            }
          })          
}
...
```

I see in the `closed` function that the library call the `return` function of each  subscriptions.
> Hmm, the `onClose` should most definitely be called. I listen for the close the same way you listen for it in the `onConnect` example:
> https://github.com/enisdenjo/graphql-ws/blob/c0b171e6fca65e0496aab70d3da84ac4c2917269/src/use/ws.ts#L107-L118
> 
> and then the `closed` call does:
> https://github.com/enisdenjo/graphql-ws/blob/c0b171e6fca65e0496aab70d3da84ac4c2917269/src/server.ts#L731-L740
> 
> Could you share a simple repro? Maybe some of the cleanup actions stall.

So in my code, the `return` function should be called and display `RETURN` in the console regardless the if the loop breaks, right ?

I tried this too (without the function returning the value):
``````js
...
subscription: {
allChannelEvent: {
            async return() {
              console.log("RETURN");
              await sleep(1000);
            },
            async throw() {
              console.log("THROW");
              await sleep(1000);
            },
            async *[Symbol.asyncIterator]() {
              const iterator = pubsub.asyncIterator(
                "$ID"
              );

              for await (const value of iterator) {
                yield {
                  allChannelEvent: value
                };
              }
            }        
}
...
```

I'm new to iterator & generator but I can't see what I'm doing wrong here unfortunatly.

**Comment by enisdenjo** [comment]
Just calling `return` does not break the loop, you must indicate that the loop is done in the `next` method too. The following example shows how to convert a `graphql-ws` subscription to an async iterator, this should help you understand how the iterator works:

_*Copied from [AsyncIterator recipe](https://github.com/enisdenjo/graphql-ws#async-iterator)_
```ts
import { createClient, SubscribePayload } from 'graphql-ws';

const client = createClient({
  url: 'wss://iterators.ftw/graphql',
});

function subscribe<T>(payload: SubscribePayload): AsyncIterableIterator<T> {
  let deferred: {
    resolve: (done: boolean) => void;
    reject: (err: unknown) => void;
  } | null = null;
  const pending: T[] = [];
  let throwMe: unknown = null,
    done = false;
  const dispose = client.subscribe<T>(payload, {
    next: (data) => {
      pending.push(data);
      deferred?.resolve(false);
    },
    error: (err) => {
      throwMe = err;
      deferred?.reject(throwMe);
    },
    complete: () => {
      done = true;
      deferred?.resolve(true);
    },
  });
  return {
    [Symbol.asyncIterator]() {
      return this;
    },
    async next() {
      if (done) return { done: true, value: undefined };
      if (throwMe) throw throwMe;
      if (pending.length) return { value: pending.shift()! };
      return (await new Promise<boolean>(
        (resolve, reject) => (deferred = { resolve, reject }),
      ))
        ? { done: true, value: undefined }
        : { value: pending.shift()! };
    },
    async return() {
      dispose();
      return { done: true, value: undefined };
    },
  };
}

(async () => {
  const subscription = subscribe({
    query: 'subscription { greetings }',
  });
  // subscription.return() to dispose

  for await (const result of subscription) {
    // next = result = { data: { greetings: 5x } }
  }
  // complete
})();
```

**Comment by c4c1us** [comment]
I understand that calling the return does not break the loop, but in my example, the `return` function wasn't called ("RETURN" wasn't display in the console).

**Comment by c4c1us** [comment]
I gonna search again, thanks for help btw.

**Comment by enisdenjo** [comment]
I suggest reading on async iterators first. I find this article quite good: https://javascript.info/async-iterators-generators.

In essence the `pubsub.asyncIterator('$ID')` should already give you a ready to use working async iterator. It might be a problem with [`graphql-subscriptions`](https://github.com/apollographql/graphql-subscriptions) too. Am not sure what is happening here; but, it seems like this part simply gets stuck:
https://github.com/enisdenjo/graphql-ws/blob/77a29812b415450806eccb704b01ded4eaf493c3/src/server.ts#L736

**Comment by c4c1us** [comment]
I found my mistake !

As you said I should use the async iterator of the `pubsub`. I previously use [Apollo Server](https://www.apollographql.com/docs/apollo-server/data/subscriptions/#production-pubsub-libraries) to handle my subscriptions. Then I move to your package and I start to iterate my async iterator ever since because It was not working when I returned it.

Why ? Because with *Apollo Server* you have to "yield" only the `value` and with *graphql-ws* `{ subscriptionName: value }`. So tried to correct an issue and I create another one. Anyway, I learn a lot about iterator / generator and *graphql-ws*.

Thanks for your help and patience ! 🙏
Have a nice day

**Comment by enisdenjo** [comment]
Glad you got it working! 🎉
