### ISSUE TITLE
Package subpath './lib/use/uWebSockets' is not defined by "exports"

### ISSUE THREAD

**Issue by vnStrawHat** [enisdenjo/graphql-ws#155]
**Screenshot**
Visualising is always helpful.
![image](https://user-images.githubusercontent.com/4435695/114648889-c298ea80-9d09-11eb-9e7b-8675b25a0514.png)

**Further Information**
Add line 80-83 like image bellow to fix this issue.
![image](https://user-images.githubusercontent.com/4435695/114649107-10adee00-9d0a-11eb-920f-a80b1cd1afac.png)

**Comment by enisdenjo** [comment]
Slipped my mind completely 😅. Thanks for brining it up, it is now fixed and released.
