### ISSUE TITLE
Question about expected retry behaviour when a subscription is unsubscribed

### ISSUE THREAD

**Issue by stevejay** [enisdenjo/graphql-ws#163]
Hi. I am successfully using graphql-ws with Apollo Client and have a graphql-ws client instance configured as follows:
- lazy set to `true`
- a keepAlive value of zero
- infinite retries

I have been testing the following scenario and I would like to know if this is the expected behaviour:

1. The WebSocket starts out as unconnected because it is lazy.
2. The user logs in and a subscription gets created. This causes a WebSocket connection to be created to the server and the subscription to be established.
3. I later simulate the server falling over by stopping it.
4. The graphql-ws client now starts retrying to connect to the server. This process proceeds as expected.
5. While the retries continue, the user logs out. This results in the subscription being unsubscribed, and so the `locks` value is decremented to zero and `complete()` is invoked.
6. Despite the `locks` value reaching zero, the retry mechanism continues to execute.

My expectation would be that retries would cease when the `locks` value reaches zero, since there is no longer a need to re-establish the connection. Is this how it should work, or is there something that I should be doing in my own code to deal with this scenario?

**Comment by enisdenjo** [comment]
Hey @stevejay, you're back with another excellent finding. 😄

This is definitely not expected, I will fix it as soon as possible. Thanks for reporting and the elaborate explanation!

**Comment by stevejay** [comment]
Thank you 👍 I've tried the bugfix version and retries now cease on logout.
