### ISSUE TITLE
Operations requested when the WebSocket is closing due to a normal closure are never handled (e.g. not sent to the server)

### ISSUE THREAD

**Issue by AlexisDeschamps** [enisdenjo/graphql-ws#173]
**Screenshot**
![image](https://user-images.githubusercontent.com/12681350/116281335-78b6f800-a73e-11eb-80f9-954a456b2795.png)

**Expected Behaviour**
Operations made soon after a client-initiated normal closure are handled the same as operations made at other times. The same problem might also exist for server-initiated normal closures but I have not tested that possibility.

**Actual Behaviour**
Starting state: the WebSocket connection was just closed by the client due to the last operation having been completed and `keepAlive` time having passed.
1. A new operation is requested
2. The following console error message appears `WebSocket is already in CLOSING or CLOSED state.`
3. The new operation from #1 is never handled (e.g. not sent to the server)

**Debug Information**
Steps to reproduce:
1. Set `lazy` to `true` and `keepAlive` to `0` on the client
2. Complete all operations
3. Start a new subscription immediately
4. See that the `WebSocket is already in CLOSING or CLOSED state.` console error message and the operation from #3 is never handled (e.g. not sent to the server)

5. Add the error code `1000` to the list of error codes here: https://github.com/enisdenjo/graphql-ws/blob/bf9acc9f0dd7b58f28b8c58296ffacf50c4426aa/src/client.ts#L503
6. Repeat steps 1-3
7. See that the operation from #3 is properly handled

**Further Information**
Suggested solutions:
- Add the error code `1000` to the list of error codes here: https://github.com/enisdenjo/graphql-ws/blob/bf9acc9f0dd7b58f28b8c58296ffacf50c4426aa/src/client.ts#L503
- Keep track of the WebSocket connection state and do not send messages if the connection is in a closing state. I'm not sure if this would catch all problems.

**Comment by enisdenjo** [comment]
@AlexisDeschamps awesome! Thank you for discovering this and for the elaborate explanation. I'll also go ahead and assume that the same issue causes #170.

Fix incoming!

**Comment by enisdenjo** [comment]
@AlexisDeschamps wondering how adding the `1000` code into fatal codes list fixes the issue... (Adding the `1000` in that array will error out the subscription, no retries will proceed)

https://github.com/enisdenjo/graphql-ws/blob/bf9acc9f0dd7b58f28b8c58296ffacf50c4426aa/src/client.ts#L500-L512

Do you have any custom retries in place?

**Comment by AlexisDeschamps** [comment]
@enisdenjo Thanks for the quick response and fix! I can confirm that upgrading to 4.4.3 has resolved the issue.

Also, sorry, I did have custom retries in place. By propagating the error, I was able to add retry logic in a different location.
