### ISSUE TITLE
Apollo client recipe only works for react

### ISSUE THREAD

**Issue by ntziolis** [enisdenjo/graphql-ws#177]
When importing from `@apollo/client` a dependency to react is introduced. Hence the sample recipes do not work when used with eg `apollo-angular`. 

Importing from `@apollo/client/core` has no react deps and hence works with all frontend frameworks (incl. react).

I added PR #176 to update the readme

**Comment by enisdenjo** [comment]
Cool stuff! I am a newb when it comes to Apollo. Thanks for brining this up!
