### ISSUE TITLE
Ability to close connection programmatically (client)

### ISSUE THREAD

**Issue by ntziolis** [enisdenjo/graphql-ws#178]
### Story

- Client is set to `lazy: false`
- User visits page not logged in
- User logs in

I want to be able to close the existing connection (after user has logged in).

So that the new connection is using the updated connection params

### Acceptance criteria

- client can be closed
- client reconnects using the new connection params

Notes:
- While it is possible to solve this by making the connection non lazy, it reduces the use cases for  `lazy: false` to situations where no re-auth is neccessary.
- We looked at the source of dispose but it doesn't look like it closes the connection when one is already open (we might be mistaken). Also it feels wrong to dispose of the entire client when all that is necessary is a reconnect.

**Comment by enisdenjo** [comment]
Hey hey, you already can. Please read the ["Client usage with graceful restart" recipe](https://github.com/enisdenjo/graphql-ws#graceful-restart). Same recipe applies to both modes, lazy or non-lazy.

Delaying the connect retry after a close can be adjusted by timing the `retryWait` promise resolution. (In case you want to close the connection and wait for the next login). For that, you can check the ["Client usage with custom retry timeout strategy" recipe](https://github.com/enisdenjo/graphql-ws#retry-strategy).

**Comment by ntziolis** [comment]
Thank you for pointing that out. This indeed does the job but it feels a little cumbersome for a commonly used action. Are you open for me to create a PR that exposes a restart method on the client directly?

**Comment by ntziolis** [comment]
Actually I think its better to solve this with a custom create function that simply returns an extended client:
```ts
type RestartableClient = Client & { restart: () => void }
```

This way people could choose if they need this or not since it does have a minor performance impact.

**Comment by enisdenjo** [comment]
The restart is intentionally not a part of the core because it has a few moving parts (socket can change due to reconnects, the restart close event can change and you can use your custom code for communicating the reason to the server) and I feel it can be achieved in user-land easily and you can have much more control. That being said, I wont implement the restart here and I think that additional package just for that function is an overkill. 

As you suggested, the restartable client can be achieved rather easy. Extending the recipe, this is how it'd look like:

```ts
import { createClient, Client, ClientOptions } from 'graphql-ws';

interface RestartableClient extends Client {
  restart(): void;
}

function createRestartableClient(options: ClientOptions): RestartableClient {
  let restartRequested = false;
  let restart = () => {
    restartRequested = true;
  };

  const client = createClient({
    ...options,
    on: {
      connected: (socket) => {
        options.on?.connected?.(socket);

        restart = () => {
          if (socket.readyState === WebSocket.OPEN) {
            // if the socket is still open for the restart, do the restart
            socket.close(4205, 'Client Restart');
          } else {
            // otherwise the socket might've closed, indicate that you want
            // a restart on the next connected event
            restartRequested = true;
          }
        };

        // just in case you were eager to restart
        if (restartRequested) {
          restartRequested = false;
          restart();
        }
      },
    },
  });

  return {
    ...client,
    restart: () => restart(),
  };
}
```

Maybe this example would be better suited for the "graceful restart" recipe? What do you think?

**Comment by ntziolis** [comment]
That's exactly what we ended up doing. And yes, using this instead as a `recipe` for graceful restart makes it much easier for folks to just plug the recipe into their own codebase.

In regards to the snippet above, I think as it is now it would override the `on` property entirely instead of just `connected`, instead it should be:

```ts
import { createClient, Client, ClientOptions } from 'graphql-ws';

interface RestartableClient extends Client {
  restart(): void;
}

function createRestartableClient(options: ClientOptions): RestartableClient {
  let restartRequested = false;
  let restart = () => {
    restartRequested = true;
  };

  const { on = undefined } = options;

  const client = createClient({
    ...options,
    on: {
      ...on,
      connected: (socket) => {
        on?.connected?.(socket);

        restart = () => {
          if (socket.readyState === WebSocket.OPEN) {
            // if the socket is still open for the restart, do the restart
            socket.close(4205, 'Client Restart');
          } else {
            // otherwise the socket might've closed, indicate that you want
            // a restart on the next connected event
            restartRequested = true;
          }
        };

        // just in case you were eager to restart
        if (restartRequested) {
          restartRequested = false;
          restart();
        }
      },
    },
  });

  return {
    ...client,
    restart: () => restart(),
  };
}
```

**Comment by enisdenjo** [comment]
Good eye! I'll redact my example in favour of yours and update the recipe accordingly. Thanks @ntziolis!

**Comment by zakharchenkoAndrii** [comment]
Why this part of the code with `restartRequested` is needed at all?
```        
  } else {
            // otherwise the socket might've closed, indicate that you want
            // a restart on the next connected event
            restartRequested = true;
          }
        };

        // just in case you were eager to restart
        if (restartRequested) {
          restartRequested = false;
          restart();
        }
```

In case the socket is not in `OPEN` state and doesn't change we will have function endlessly calling itself until `OutOfMemory` .

cc/ @enisdenjo @ntziolis

**Comment by enisdenjo** [comment]
The `restartRequested` is needed in case `restart()` was called before the socket connected, it's like queuing up a restart.

It won't call itself endlessly because the `connected` event is invoked only once when connected, if `restartRequested = true` it will reset the request by setting it to false and restart the open socket. Next time `connected` is called, `restartRequested = false`.

**Comment by zakharchenkoAndrii** [comment]
Ohhhh, I got it! Thank you for the detailed explanation <3!
