### ISSUE TITLE
Access to socket instance on client to send arbitrary messages from the browser

### ISSUE THREAD

**Issue by skk2142** [enisdenjo/graphql-ws#184]
I want to send some mutations from the client over websocket. Since this library does not support sending mutations over websocket, I want to access the raw socket to emit data. Would it be possible to expose the socket inside the `Client` object in the browser?

**Comment by enisdenjo** [comment]
This library and the [GraphQL over WebSocket Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#query-and-mutation-operations-without-streaming-directives) supports all operations (including mutations). 

Out of curiosity, what made you think it doesnt?

**Comment by skk2142** [comment]
Ah I somehow overlooked! Thank you!
