### ISSUE TITLE
Error "Closing a missing client" on connection

### ISSUE THREAD

**Issue by dalisoft** [enisdenjo/graphql-ws#186]
**Screenshot**
<img width="2560" alt="Снимок экрана 2021-05-26 в 19 43 01" src="https://user-images.githubusercontent.com/3511344/119680399-97520100-be5a-11eb-99cf-7af2cd5a31e8.png">

**Expected Behaviour**
Running like excepted

**Actual Behaviour**
```bash
[Server]: started successfully at [localhost:4000] in [4ms]
file:///Users/dalisoft/Desktop/Open_Source/nanoexpress/plugins/middlewares/packages/graphql/examples/node_modules/graphql-ws/lib/use/uWebSockets.mjs:103
                throw new Error('Closing a missing client');
                ^

Error: Closing a missing client
    at close (file:///Users/dalisoft/Desktop/Open_Source/nanoexpress/plugins/middlewares/packages/graphql/examples/node_modules/graphql-ws/lib/use/uWebSockets.mjs:103:23)
    at Object.close (file:///Users/dalisoft/Desktop/Open_Source/nanoexpress/plugins/middlewares/packages/graphql/examples/node_modules/graphql-ws/lib/use/uWebSockets.mjs:65:28)
    at Object.opened (file:///Users/dalisoft/Desktop/Open_Source/nanoexpress/plugins/middlewares/packages/graphql/examples/node_modules/graphql-ws/lib/server.mjs:37:24)
    at open (file:///Users/dalisoft/Desktop/Open_Source/nanoexpress/plugins/middlewares/packages/graphql/examples/node_modules/graphql-ws/lib/use/uWebSockets.mjs:57:36)
    at upgrade (file:///Users/dalisoft/Desktop/Open_Source/nanoexpress/plugins/middlewares/packages/graphql/examples/node_modules/graphql-ws/lib/use/uWebSockets.mjs:39:17)

```

**Debug Information**
OS: macOS Big Sur 11.4 (Intel x64)
Node: v16.2.0

**Further Information**
It sometimes work, sometimes don't

**Minimal reproducible repository**
https://github.com/nanoexpress/middlewares/tree/master/packages/graphql/examples

**Comment by enisdenjo** [comment]
Hey there! Thanks for reporting and testing uWebSockets. This seems like a bug, but through a brief look over the code - I dont know why.

Nevertheless, I will take a deeper look very soon and will report my findings. 😄

**Comment by dalisoft** [comment]
@enisdenjo Thank you. I also will try debug and find why it happens.

**Comment by enisdenjo** [comment]
The following part is the only one that deletes clients/sockets from the [clients map](https://github.com/enisdenjo/graphql-ws/blob/5e37be8b6c0943ad100f65580c28409623b3a138/src/use/uWebSockets.ts#L48) and is the only place where that specific error can occur:
https://github.com/enisdenjo/graphql-ws/blob/5e37be8b6c0943ad100f65580c28409623b3a138/src/use/uWebSockets.ts#L140-L151
Looks like it gets called multiple times for the same socket... The "why?" is what needs answering.

**Comment by dalisoft** [comment]
Or maybe socket opening does not happening
https://github.com/enisdenjo/graphql-ws/blob/5e37be8b6c0943ad100f65580c28409623b3a138/src/use/uWebSockets.ts#L145

**Comment by enisdenjo** [comment]
Hmm, might happen. I add the client to the map once I prepared it:
https://github.com/enisdenjo/graphql-ws/blob/5e37be8b6c0943ad100f65580c28409623b3a138/src/use/uWebSockets.ts#L121
But, as JS is single threaded, and there is no async code in the `open` callback, I expect it to always be added.

However, since uWS is powered by C++, there could be some "magic" happening behind the curtains terminating `open` early or not calling it at all (the latter being more likely).

**Comment by dalisoft** [comment]
Yea, I’ll try debug in next two days or next week and maybe we fix it together or i let you know where has been bug

**Comment by enisdenjo** [comment]
Figured out why. It happens when you request a WebSocket upgrade with a wrong subprotocol (for example with `subscriptions-transport-ws`, which is the default for Altair).

Establishing a connection with a wrong subprotocol immediately closes the connection:
https://github.com/enisdenjo/graphql-ws/blob/5e37be8b6c0943ad100f65580c28409623b3a138/src/use/uWebSockets.ts#L106

The client is not added to the map since `socket.end` calls the `close` callback synchronously.

**Comment by dalisoft** [comment]
For me it started working after these actions:
1. Restarting machine
2. Go-to directory
3. `rm -rf node_modules yarn.lock`
4. yarn cache clean
5. yarn
6. Running script
7. Run Altair (protocol already have been "Websocket (graphql-ws)")

**Comment by enisdenjo** [comment]
Seems like a bug with Altair. Having selected "Websockets" once, even after changing it, it will try connecting with the legacy protocol automatically in the background (which is why it happened sometimes for you).

Glad you like `graphql-ws` and thank you for the kind words! 😄

**Comment by dalisoft** [comment]
If you need HTTP GraphQL, you can use [this](https://github.com/nanoexpress/middlewares/tree/master/packages/graphql) with framework, it's really fast. [Here examples](https://github.com/nanoexpress/middlewares/tree/master/packages/graphql/examples) which uses `graphql-ws` when need need to use `Subscription` and it's too really very very fast.

**Comment by enisdenjo** [comment]
Awesome! Nice to hear that the library can be speedy. I wanted to do some benchmarks; but honestly, dont know where to start. Any pointers? How'd you measure the speed over at `nanoexpress`?

**Comment by dalisoft** [comment]
Benchmark.js, console.time for any function compare or Websocket connection time compare. 

wrk for http

**Comment by dalisoft** [comment]
Or you can [try this](https://github.com/uNetworking/uWebSockets/blob/master/benchmarks/broadcast_test.c) as uWebSockets uses this way. I used it once, seems good way, but not easy to run
