### ISSUE TITLE
[Question] Meteor/Apollo Subscriptions

### ISSUE THREAD

**Issue by ajaypillay** [enisdenjo/graphql-ws#187]
Hi, I'm running a Meteor/Apollo/React stack and I was trying to get Graphql Subscriptions working and I came across this package. However, there isn't an example of implementation using Meteor/Apollo.

Would anyone be able to advise on how to proceed with this?

Currently on my server I have:
```
const schema = makeExecutableSchema({
    typeDefs,
    resolvers,
})
const context = async ({req}) => ({
    user: await getUser(req.headers.authorization)
})
const server = new ApolloServer({
    schema,
    context
})
server.applyMiddleware({
    app: WebApp.connectHandlers,
    path: "/graphql",
})
WebApp.connectHandlers.use("/graphql", (req, res) => {
    if (req.method === "GET") {
        res.end()
    }
})
```
And on my client I have:
```
const httpLink = new HttpLink({
    uri: "http://XXX.XXX.XX.XX:3000/graphql"
})
const authLink = new ApolloLink((operation, forward) => {
    const token = Accounts._storedLoginToken()
    operation.setContext(() => ({
        headers: {
            authorization: token
        }
    }))
    return forward(operation)
})
const client = new ApolloClient({
    link: from([authLink, httpLink]),
    cache: new InMemoryCache()
})
const ApolloApp = () => (
    <BrowserRouter>
        <ApolloProvider client={client}>
            <App client={client} />
        </ApolloProvider>
    </BrowserRouter>
)
Meteor.startup(() => {
    render(<ApolloApp />, document.getElementById("app"))
})
```
How should I go about configuring this to allow for subscriptions? Meteor does have the [swydo:ddp-apollo](https://github.com/Swydo/ddp-apollo) package but I've not been able to set that up correctly and one of the drawbacks is that Graphiql will no longer be available. I can't depend on Apollo Dev Tools right now either because it doesn't open up Graphiql either regardless of server configuration (already filed a bug for this, it just shows up as blank).

If there's some way I can use this package to get subscriptions working, that would be great. Appreciate any help, thank you.

**Comment by enisdenjo** [comment]
Hey there! Sadly I have no experience with Apollo whatsoever, and very little with Meteor (years ago I've used it).

Briefly looking at the mentioned `ddp-apollo` library, seems like it uses [a custom WebSocket protocol for the ApolloLink](https://github.com/Swydo/ddp-apollo/blob/838abfaa17cf6b1291ffbf71035b694d2bbb235b/packages/apollo-link-ddp/src/client/apollo-link-ddp.js#L68-L122). For `graphql-ws` to work, both the client and the server must implement [the GraphQL over WebSocket Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md). There is, however, a ["Client usage with Apollo" recipe](https://github.com/enisdenjo/graphql-ws#apollo-client) showcasing how to create a `graphql-ws` compatible ApolloLink.

Regarding the server, [Meteor exports the `webapp` package](https://docs.meteor.com/packages/webapp.html) that lets you hook up your own server logic. Dont know how exactly, but I am very certain that you can provide your own WebSocket server implementation (use the abundance of [ws server recipes](https://github.com/enisdenjo/graphql-ws#recipes) to help you start).

**Comment by ajaypillay** [comment]
Hi, sorry for the late response as I had to work on other aspects of the app I'm building.

I will be working on this shortly and will look into your suggestions and will update here once I have made any progress. Thanks a lot for the explanation and links.
