### ISSUE TITLE
SubscribePayload support for query/id

### ISSUE THREAD

**Issue by artola** [enisdenjo/graphql-ws#188]
**Source code**
https://github.com/enisdenjo/graphql-ws/blob/e3b81fab8fbd4df41e773912d5f352271cb1efc0/src/common.ts#L93

**Expected Behaviour**
`SubscribePayload` should support `query` (text) or `id` (hashed query) for `persisted queries` (might be an union type).

**Actual Behaviour**
Only `query` is allowed and it is `required`.

**Comment by enisdenjo** [comment]
Hey there! Simply use the `query` field to transmit the hash ID. Please check the ["ws server and client usage with persisted queries" recipe](https://github.com/enisdenjo/graphql-ws#persisted).

**Comment by artola** [comment]
@enisdenjo Thanks and sorry, I did not see the recipe.

**Comment by enisdenjo** [comment]
Hey @artola, quick heads up: [`graphql-ws@v4.7.0`](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.7.0) just landed, [adding the `extensions` field in the subscribe message payload](https://github.com/enisdenjo/graphql-ws/commit/d86a8e472a32aa4a12f6794f90ca2419f9f87fdb).

This means that you now can pass along the `persistedQuery` through that field on each subscribe as various other libraries/frameworks suggest.

**Comment by artola** [comment]
@enisdenjo Thanks for the info. But still I have my doubts about the `query` property as you know still it is required.
https://github.com/enisdenjo/graphql-ws/blob/2933997cfbbe9965a52acadb0a727e6dfb87b265/src/common.ts#L95

In our case, we need to send of the query the `text` on development, and the `id` (hash) on production. We do this already with queries and mutations, where we have something like this:

```
{
  id?: string;  // operation.id
  query?: string; // operation.text
} 
```
In this way. the server can use for performance and security the `id` when available else will parse the `query`.

Having both values mixed in the subscription will lead to a lot of troubles. Of course we can send the value as we eant anyway, as part of the "spec" it is not nice.

**Comment by michaelstaib** [comment]
@enisdenjo @artola lets do a PR to the actual HTTP spec to first get this change into the HTTP spec. I spoke to @IvanGoncharov about persisted queries a while ago and the general idea was to move the top-level `id` into extensions. But we never actually discussed that `query` can become optional in the  you pass along `id`. In general that would mean `query` can be null when extension is set. The validation is then up to the server. 

This for instance this how an apollo persisted query request looks like.

```json
{
  "extensions": {
    "persistedQuery": {
      "version": 1,
      "sha256Hash": "ecf4edb46db40b5132295c0291d62fb65d6759a9eedfa4d5d612dd5ec54a6b38"
    }
  }
}
```

So let me do a PR to the HTTP spec and then discuss things on that repo.

**Comment by michaelstaib** [comment]
I will write something to the following issue:
https://github.com/graphql/graphql-over-http/issues/38

**Comment by enisdenjo** [comment]
I try mirroring the HTTP spec as much as possible.

Having said that, if we make the `query` field optional there, no reason to keep it required in the WS spec.
