### ISSUE TITLE
Store custom extra data on the context object

### ISSUE THREAD

**Issue by idevelop** [enisdenjo/graphql-ws#189]
Apologies if I missed this in the documentation, just wondering how I would go about storing some specific extra data in the `context.extra` field? As far as I can tell, that field is typed as only storing the objects that result from the server initialisation (websocket, http request, etc), and there doesn't seem to be a way for me to extend that `Extra` type when creating the server.

My use case is: in the `onConnect` callback, after validating the auth token the client provides in `connectionParams`, I'd like to create a `Session` object (containing userID, some user-specific objects, etc), that then becomes available to the resolvers. 

As I understand from the documentation, the `context` callback is called on every operation so it's not really suitable for this, since ideally I'd like to not re-validate the auth token and recreate the `Session` object on every single operation, since it would be very wasteful. So my next thought was to store that `Session` object in the `context.extra` object, but that doesn't seem to be possible. 

Thanks!

**Comment by idevelop** [comment]
This seems to work but needs some @ts-ignore comments:

```js
makeBehavior({
  onConnect: async (ctx) => {
    // @ts-ignore
    ctx.extra.context = await authenticatedRequestContext(ctx.connectionParams);
    return true;
  },
  // @ts-ignore
  context: (ctx) => ctx.extra.context,
})
```

**Comment by enisdenjo** [comment]
The context extra is meant to be created when opening connections, this is why you are able to set the generic through [`makeServer`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/modules/server.md#makeserver) and provide the extra through [the `opened` method](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.server-1.md#opened) used for implementing your own WS server. You're absolutely free to implement your own server and use the `makeServer` with the most relevant context extras for you.

However, the context extras are meant to be used by the user; meaning, you're free to assign whatever and whenever you want to `ctx.extra` (exactly how you did in https://github.com/enisdenjo/graphql-ws/issues/189#issuecomment-851008738). 

But, you're indeed right about it not being typed and how strenuous that might be. Maybe provide an extra generic for both `ws.useServer` and `uws.makeBehaviour` that extends the context extra typings and allows you to have a type safe extra object?

Furthermore, just wanted to point out an important distinction: the `ctx` argument is the WebSocket connection context and the `context` option is the GraphQL `contextValue`.

**Comment by idevelop** [comment]
> Maybe provide an extra generic for both ws.useServer and uws.makeBehaviour that extends the context extra typings and allows you to have a type safe extra object?

Thanks for clarifying, that would be nice yeah! 

Something like
```ts
export declare function makeBehavior<T = {}>(options: ServerOptions<Extra & Partial<T>> ...);
```
```ts
makeBehavior<{ session: Session }>(...)
```

The `Partial` there is to allow for the user-provided Extra fields to be undefined between the connection being established and when `onConnect` has had a chance to populate them with real values.

**Comment by enisdenjo** [comment]
Makes sense! Lets see what I can do.
