### ISSUE TITLE
graphql-ws + uWebSockets.js: subscription/type resolvers questions

### ISSUE THREAD

**Issue by idevelop** [enisdenjo/graphql-ws#190]
We have an existing Apollo server that uses `subscriptions-transport-ws` that I'd like to migrate to `graphql-ws` with `uws`, and I'm having some issues reusing our existing resolvers.

The example suggests the `makeBehavior` function which accepts `schema` (pretty straightforward) and `roots`. 
This `roots` object is where I'm getting a bit lost:

1. How do I declare resolvers for specific GraphQL types? It seems like I can only declare the top level operation resolvers (`query`, `mutation`, `subscription`), so in this `roots` model, where do I pass the reference that, for example, when resolving the `User` graphQL type it must use a specific `userResolver` function?

2. Our existing subscription resolvers are objects that have a `subscribe` function (which returns the `AsyncIterator`) + a `resolve` function which allows transforming the pubsub payload before forwarding it to the client. When passing the Apollo subscription resolvers into the roots object (`roots: { subscription: apolloResolvers.Subscription } }`, I get this runtime `CloseEvent` error: `Subscription field must return Async Iterable. Received: { resolve: [function resolve], subscribe: [function subscribe]`. What am I missing? Are subscription `resolve` functions an Apollo-specific feature that is impossible to have outside of it? I came across the `graphql-subscriptions` package as well today but I'm unclear if it's useful in resolving this issue.

Really looking forward to finally dropping `graphql-ws` into our server to replace `subscriptions-transport-ws`, thanks for all the support!

**Comment by idevelop** [comment]
I was able to resolve both of these with the `addResolversToSchema` function from `@graphql-tools/schema`:
```
schema: addResolversToSchema({
  schema: buildASTSchema(schema),
  resolvers: apolloResolvers,
}),
roots: {
  query: apolloResolvers.Query,
  mutation: apolloResolvers.Mutation,
  subscription: apolloResolvers.Subscription,
},
```

**Comment by enisdenjo** [comment]
Am very glad you decided to continue with `graphql-ws`! 😄 

Both your questions are actually about `graphql`, not really related to `graphql-ws`. I'll start by saying that the `roots` option is just a convenience, you should implement all your resolvers and logic completely in the `schema`. There are many ways of doing so and many libraries helping you ease the process up, I recommend Googling - but it all boils down to your preference. Nevertheless, using [`graphql-tools`](https://github.com/ardatan/graphql-tools) is something I'd recommend.

1. The matching operation type from the `roots` option is simply used as the execution's `rootValue`.
  https://github.com/enisdenjo/graphql-ws/blob/e3b81fab8fbd4df41e773912d5f352271cb1efc0/src/server.ts#L700-L701
2. As the error states, "Subscription field must return Async Iterable.", is exactly what is happening there (the field resolver must have a `subscribe` method and it must return an async iterable). Please check your schema implementation.

P.S. I have absolutely 0 experience with Apollo, so I cannot really shine any light about Apollo specific issues, sorry.

**Comment by idevelop** [comment]
> Both your questions are actually about `graphql`, not really related to `graphql-ws`.

That's fair, thanks for clarifying! One disadvantage of using libraries like Apollo is that they do so much in a black box that it blurs the line for the developer between generic graphQL functionality and what value they provide on top of that. 

Similarly, as I'm faced with the prospect of switching it out for a combination of `ws`/`uws` for the network layer, `graphql-ws` for the protocol, and plain `graphql` for execution, it's hard to say what I'm losing by not using Apollo, as from the outside it looks more or less the same.

> I'll start by saying that the roots option is just a convenience, you should implement all your resolvers and logic completely in the schema.

You're right, everything still works if I remove the `roots` variable there, seems like all behaviour is now contained in the schema with resolvers.

**Comment by enisdenjo** [comment]
> One disadvantage of using libraries like Apollo is that they do so much in a black box

100% behind you on that. Personally, am not a big fan of tooling. I like getting my hands dirty in favour of control. When you play with low level stuff, you find more efficient and intricate ways of solving complex solutions by understanding the fundamentals.

Nevertheless, glad you got it working! If you're satisfied with the answers, please close the issue.

**Comment by idevelop** [comment]
Thanks again!
