### ISSUE TITLE
ws usage with apollo server express example: could not connect to websocket endpoint

### ISSUE THREAD

**Issue by msadovyi** [enisdenjo/graphql-ws#202]
Hi, I'm trying to use graphql-ws for subscriptions using your examples for Express Apollo Server:
index.js
```
const ws = require('ws');
const express = require('express');
const { ApolloServer } = require('apollo-server-express');
const { useServer } = require('graphql-ws/lib/use/ws');
const { buildSchema } = require('graphql');

const schema = buildSchema(`
  type Query {
    hello: String
  }
  type Subscription {
    greetings: String
  }
`);

const roots = {
  query: {
    hello: () => 'Hello World!',
  },
  subscription: {
    greetings: async function* sayHiIn5Languages() {
      for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
        yield { greetings: hi };
      }
    },
  },
};

const app = express();
const apolloServer = new ApolloServer({ schema, playground: true });

apolloServer.applyMiddleware({ app });

const server = app.listen(4000, () => {
  const wsServer = new ws.Server({
    port: 80,
    path: '/graphql',
  });

  useServer({ schema, roots }, wsServer);
});
```
**Expected Behaviour**
Run `node index`, go to playground `http://localhost:4000/graphql`
The following query should return "Hi" in 5 languages:
```
subscription {
  greetings
}
```

**Actual Behaviour**
The subscription above returns the following error: 
```
{
  "error": "Could not connect to websocket endpoint ws://localhost:4000/graphql. Please check if the endpoint url is correct."
}
```

What am I doing wrong? Thanks!

**Comment by enisdenjo** [comment]
Hey there! You're actually creating another WebSocket server on port 80. As shown in the ["ws server usage with Apollo Server Express" recipe](https://github.com/enisdenjo/graphql-ws#apollo-server-express), you have to pass in the `server` to the ws.Server, instead of setting the port.

```diff
const server = app.listen(4000, () => {
  const wsServer = new ws.Server({
-   port: 80,
+   server,
    path: '/graphql',
  });

  useServer({ schema, roots }, wsServer);
});
```

**Comment by enisdenjo** [comment]
Also note that `graphql-playground` is using the legacy `subscriptions-transport-ws` (you cannot use it with `graphql-ws`). 

There is an issue requesting `graphql-ws` integration on their side https://github.com/graphql/graphql-playground/issues/1291. You can track its progress there.

I recommend using `graphiql` instead. For testing WebSockets only, you can use this gist: https://gist.github.com/enisdenjo/a68312878fdc4df299cb0433c60c1dea (simply download to an HTML file, set the `url` and open it in your favourite browser).

**Comment by msadovyi** [comment]
Big thanks!
