### ISSUE TITLE
Undefined error if Subscription starts with capital letter in roots

### ISSUE THREAD

**Issue by vladshcherbin** [enisdenjo/graphql-ws#205]
**Screenshot**

![image](https://user-images.githubusercontent.com/6711845/122091852-ed8ae200-ce11-11eb-8c2d-f37d36860958.png)

**Expected Behaviour**

There should not be an error if `Subscription` is used in `roots`.

**Actual Behaviour**

There is an `undefined` error if `Subscription` starts with a capital letter.
When using graphql server and graphql-tools, there is no such error 🤔

**Debug Information**

From docs, capitalize `subscription` first letter:

```js
roots: {
  Subscription: {
    greetings: async function* sayHiIn5Languages() {
      for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
        yield { greetings: hi }
      }
    }
  }
}
``` 

**Further Information**

Trying to move from deprecated `subscriptions-transport-ws` 🙈

**Comment by vladshcherbin** [comment]
I also have this error when trying to use existing schema (which uses [graphql-tools](https://www.graphql-tools.com/docs/generate-schema)):

<details>
 <summary>Full example</summary>

```js
import { makeExecutableSchema } from '@graphql-tools/schema'
import { useServer } from 'graphql-ws/lib/use/ws'
import ws from 'ws'

const wserver = new ws.Server({
  port: 5000,
  path: '/graphql'
})

const typeDefs = [
  `
    type Query {
      hello: String
    }
    type Subscription {
      greetings: String
    }
  `
]

const resolvers = {
  Subscription: {
    greetings: async function* sayHiIn5Languages() {
      for (const hi of ['Hi', 'Bonjour', 'Hola', 'Ciao', 'Zdravo']) {
        yield { greetings: hi }
      }
    }
  }
}

const schema = makeExecutableSchema({
  typeDefs,
  resolvers
})

useServer(
  {
    schema
  },
  wserver
)

console.log('Listening to port 5000')
```
</details>

**Comment by vladshcherbin** [comment]
I believe it's coming from here https://github.com/enisdenjo/graphql-ws/blob/master/src/server.ts#L728.

Quick changing line to `Subscription` passes `undefined` error but above example (from second message) gives another error:

```
{ "errors": [ { "message": "String cannot represent value: {}", "locations": [ { "line": 3, "column": 3 } ], "path": [ "greetings" ] } ], "data": { "greetings": null } }
```

🙈

**Comment by enisdenjo** [comment]
Out of curiosity, which app are you using in the screenshot (An error occurred in subscription.)?

**Comment by vladshcherbin** [comment]
@enisdenjo it's an awesome [altair](https://github.com/imolorhe/altair) app. I think it can't find correct error message and tricked me with `undefined` message.

I've added loggers to all `on*` events, trying to fully migrate to `graphql-ws`, with auth, existing server and existing schema. Currently gathering your suggestions on auth from various issues in different repositories 😅
Will try to resolve my schema error from your reply, still new to gql subscriptions.

Thank you for this library! I'd also love to see your _recipies_ in docs and follow them (on auth, error handling).

We also have ios and androind clients so the road is full of fun 🙈

**Comment by enisdenjo** [comment]
Yeah, there should be a more communicative error message there... I guess an issue for Altair. Thanks for sharing!

My suggestion on auth is in [the "ws server and client auth usage with token expiration, validation and refresh" recipe](https://github.com/enisdenjo/graphql-ws#auth-token). Do check it out. 😄

**Comment by krvajal** [comment]
> The roots object expects lowercase operation names.

This is a weird decision, considering that the type in the schema are called `Mutation`, `Query` and `Subscription`, but no much we can do about it I assume.

From your comment it is not clear if it is only for those or if I have a type `User`, should it be lowercased as well @enisdenjo ?

**Comment by enisdenjo** [comment]
> This is a weird decision, considering that the type in the schema are called Mutation, Query and Subscription, but no much we can do about it I assume.

@krvajal, not a weird decision. The `roots` option is passed directly to GraphQL's execute/subscribe `rootValue` following the operation AST. Quoting [the comment you referenced](https://github.com/enisdenjo/graphql-ws/issues/205#issuecomment-862165684):

> ... the detected operation type root is put directly in the execute/subscribe `rootValue` argument: https://github.com/enisdenjo/graphql-ws/blob/4f11c8aeec092fac21bee6c9084f1e622b5e4a41/src/server.ts#L716

_*Read more about the `rootValue` in [this StackOverflow answer](https://stackoverflow.com/a/54309820/3633671)._

> From your comment it is not clear if it is only for those or if I have a type `User`, should it be lowercased as well.

GraphQL's execute/subscribe `rootValue` is only available to root level resolvers.

---

Also from the [the comment you referenced](https://github.com/enisdenjo/graphql-ws/issues/205#issuecomment-862165684):
> ... the `roots` option is **just a convenience**. You should absolutely use only the `schema` option as you attempted.

This is a WebSocket transport library, not a schema building/tooling library. There's an abundance of those around the internet (I recommend taking a look at [`graphql-tools`](https://www.graphql-tools.com/)). You should definitely construct your schema using GraphQL primitives (or tools) first, and then supply the resulting single schema to `graphql-ws`'s server `schema` option.
