### ISSUE TITLE
Provide hook to close socket (server side)

### ISSUE THREAD

**Issue by tot-ra** [enisdenjo/graphql-ws#218]
### Story
As a user of ws server
I want to close socket in ws server **after** connection with the client has been established & subscriptions established, 
because context of clients can change later (customers are deleted, deactivated, permissions changed etc after they got access to streaming data).

We can limit authentication with some expiration logic, but we need to be able to close existing connections (not just stop passing the data to them using resolver filters)

### Possible solutions
- (max freedom / traditional OOP) server injects `ctx.socket` to all existing hooks. Then we can add separate watcher in `onConnect` hook to operate socket close the connection at will
https://github.com/enisdenjo/graphql-ws/blob/master/src/server.ts#L539
- (min freedom / functional) server provides functional hook `onConnected(ctx, closeConnection)` maybe with message as argument. 
- (no change needed?) maybe there is a way to have two async iterators to join both DATA and USER changes in one stream & if there is user change - throw Error (that maybe could trigger disconnect?). I'm not sure if this is possible

**Comment by tot-ra** [comment]
oops. looks like `ctx.extra.socket.close()` already is available in `onConnect`. Closing

**Comment by enisdenjo** [comment]
You can already close the socket through the `ctx.extra.socket` whenever you want. Please read the ["ws server and client auth usage with token expiration, validation and refresh" recipe](https://github.com/enisdenjo/graphql-ws#auth-token).
