### ISSUE TITLE
graphql-ws/Client : Infinite loop when missing credentials 

### ISSUE THREAD

**Issue by nomocas** [enisdenjo/graphql-ws#244]
Hello All, 

Client graphql-ws v5.5.0 
on nodejs v14.17.0

Server : Hasura v2.0.9

**Expected Behaviour**
I expected graphql-ws/client to show an error when server does not accept connexion because missing credentials.

**Actual Behaviour**
Instead it loops infinitely (without any error). So if you do not have acces to server's logs, you simply don't understand why such behaviour happen.

To reproduce : simply setup a server (by example hasura >= v2.0.8) that needs credentials, try to connect with graphql-ws/client without providing credentials. Boom : it loops.

By the way, there is nowhere in the documentation a clear explanation about how to setup credentials in the client.

For those who are looking for it (example with hasura) :
```javascript
    const client = createClient({
       ...
        connectionParams: {
            headers: {
                'x-hasura-admin-secret': '...',
            },
        },
       ...
   })
```

**Comment by enisdenjo** [comment]
What loops infinitely? Client keeps trying to reconnect? For the client to fail right away, set the `retryAttempts` client option to zero (0).

The default for the client is to silently try reconnecting 5 times with randomized exponential back-off and then fail. Please check out the [`retryAttempts`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#retryattempts) and [`retryWait`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#retrywait) client options.

**Comment by enisdenjo** [comment]
Please provide me with the close reason.
```diff
import { createClient, ExecutionResult, SubscribePayload, Client } from 'graphql-ws';
import ws from 'ws';
import { v4 } from 'uuid';
import dbg from 'debug';

export { SubscribePayload, ExecutionResult };

const debug = dbg('hpk:graphql-ws');

export function createGQLClient(url: string) {
    debug('createGQLClient(%s)', url);
    const client = createClient({
        url,
        webSocketImpl: ws,
        generateID: () => v4(),
        connectionParams: {
            headers: {
                // this should be removed to have the bug
                'x-hasura-admin-secret': process.env.HASURA_GRAPHQL_ADMIN_SECRET as string,
            },
        },
        on: {
            connected: () => {
                debug('connected');
            },
            connecting: () => {
                debug('connecting');
            },
            opened: () => {
                debug('opened');
            },
-           closed: () => {
-               debug('closed');
-           },
+           closed: (err) => {
+               debug('closed', err.code, err.reason); // 👈
+          },
            message: (msg) => {
                debug('message', msg);
            },
            ping: (msg) => {
                debug('ping', msg);
            },
            pong: (msg) => {
                debug('pong', msg);
            },
            error: (err) => {
                debug('error');
                console.error(err);
            },
        },
        onNonLazyError: (errorOrCloseEvent) => {
            debug('NonLazyError');
            console.error(errorOrCloseEvent);
        },
    });

    client.on('error', (err) => {
        debug('client error');
        console.error(err);
    });
    return client;
}

```

**Comment by nomocas** [comment]
Ok so hasura send two codes ? 
1000 as main error code and 4400 as reason code ?

What should I do to have this fixed ?

**Comment by enisdenjo** [comment]
I am closing this issue in favor of https://github.com/hasura/graphql-engine/issues/7696. As soon as it gets resolved there, it will work as expected here.
