### ISSUE TITLE
Is it possible to use express-session for cookie-based authentication?

### ISSUE THREAD

**Issue by pedromsfernandes** [enisdenjo/graphql-ws#256]
I have a NestJS server and an Apollo client with `graphql-ws`. I am using cookie-based authentication for my queries and mutations, and now I also need to authenticate the user in my subscriptions. Problem is, in every guide I've seen, only token-based auth is used. I found [this issue](https://github.com/apollographql/subscriptions-transport-ws/issues/466) which provides a solution, however that library is not maintained and as far as I know, graphql-ws `onConnect` method does not provide a `ws` argument. Can `connectionParams` be used for this? Thanks!

EDIT: I've noticed there's a discussions tab that seems to be better suited for this kind of question.

**Comment by enisdenjo** [comment]
Moved to https://github.com/enisdenjo/graphql-ws/discussions/257.
