### ISSUE TITLE
running code examples

### ISSUE THREAD

**Issue by sibelius** [enisdenjo/graphql-ws#26]
Thanks for making this, it looks awesome

I think it would make it easier and more appealing to have some github repo where you can clone and run to play with this implementation

we could have a monorepo with this matrix of implementations:

## server
- [ ] pure http server (not sure if anybody is using this in production)
- [ ] express
- [ ] koa

## frontend
- [ ] relay
- [ ] apollo
- [ ] urlq
- [ ] "pure"

**Comment by n1ru4l** [comment]
You could start from here: https://github.com/n1ru4l/graphql-live-queries/tree/main/packages/todo-example

**Comment by enisdenjo** [comment]
Hey @sibelius,

thanks for the nice words, I appreciate it!

You are right, it would be very appealing having an examples directory/repo which is 1-2 commands away from starting a runnable example.

I will see if I can hook something up in this repo (just to keep stuff at one place).

**Comment by enisdenjo** [comment]
Yeah, I never got around doing this... 😅

I now think that it might be unnecessary following the abundance of recipes.

So @sibelius, if you are interested on setting up a separate monorepo with running examples - that would be awesome! I'd be happy to help you out and, if done good enough, put up a link to the live examples directly in the readme.

That being said, I am closing this ticket.
