### ISSUE TITLE
onError is NOT being called when an Error is thrown

### ISSUE THREAD

**Issue by asadhazara** [enisdenjo/graphql-ws#286]
**Expected Behaviour**
When an Error is thrown in a resolver `onError` passed to useServer should be called.

**Actual Behaviour**
When an Error is thrown in a resolver `onNext` is called, instead of `onError`.

**Comment by enisdenjo** [comment]
Errors thrown in resolvers are fatal by nature, and if you don't handle them yourself, the WebSocket connection gets terminated.

> When an Error is thrown in a resolver onNext is called, instead of onError.

Are you sure that the error is **really** thrown and not a part of the operation result? If you are, please be kind and provide me with a repro - I'll take a look ASAP.

**Comment by asadhazara** [comment]
Please check https://github.com/asadhazara/GraphQL-over-WebSockets for an example in which this issue occurs.

**Comment by enisdenjo** [comment]
Right, errors thrown in GraphQLSchema resolvers do not bubble, but are instead added to the operation result. The `result` argument in the `onNext(_ctx, _msg, _args, result)` hook will contain all errors thrown from problematic resolvers in the `errors` field.

Note that this is **expected behavior of `graphql`** and you should make sure to always check the execution result and handle errors accordingly.

FYI, can be simply confirmed with vanilla `graphql` like this:
```js
import {
  GraphQLSchema,
  GraphQLObjectType,
  GraphQLString,
  execute,
  parse,
} from 'graphql';

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'Query',
    fields: {
      hello: {
        type: GraphQLString,
        resolve() {
          throw new Error('Something went wrong');
        },
      },
    },
  }),
});

try {
  const result = execute({
    schema,
    document: parse('{ hello }'),
  });

  const errors = result.errors;
  console.error(errors); // will contain the "Something went wrong" error

  const data = result.data;
  console.log(data); // will contain no data
} catch (err) {
  // ❌ WILL NOT be reached
}
```

**Comment by asadhazara** [comment]
I feels a little weird to handle my errors in `onError` and in `onNext` when I want to format my errors.

Maybe you could introduce a `customFormatErrorFn` like `express-graphql` arg which we can pass into useServer?

```ts
import { GraphQLObjectType, GraphQLSchema, GraphQLString } from "graphql";
import { useServer } from "graphql-ws/lib/use/ws";
import { WebSocketServer } from "ws";

const Query = new GraphQLObjectType({
  name: "Query",
  fields: {
    hello: {
      type: GraphQLString,
      resolve() {
        throw new Error("Something went wrong");
      },
    },
  },
});

const schema = new GraphQLSchema({
  query: Query,
});

useServer(
  {
    schema,
    customFormatErrorFn: (error) => {
      error.message  = 'Internal Error'

      return error
    },
    onError: () => {
      console.log("Error thrown");
    },
    onNext: () => {
      console.log("Result returned");
    },
  },
  new WebSocketServer({ port: 4000 })
);
```

**Comment by enisdenjo** [comment]
I won't add a `customFormatErrorFn` because `graphql-ws` does not (and should not) care about what the contents of an operation result is.

Nevertheless, you can format your errors directly in the [`onNext` hook](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.ServerOptions.md#onnext), roughly:
```js
import { GraphQLObjectType, GraphQLSchema, GraphQLString } from 'graphql';
import { useServer } from 'graphql-ws/lib/use/ws';
import { WebSocketServer } from 'ws';

const Query = new GraphQLObjectType({
  name: 'Query',
  fields: {
    hello: {
      type: GraphQLString,
      resolve() {
        throw new Error('Something went wrong');
      },
    },
  },
});

const schema = new GraphQLSchema({
  query: Query,
});

useServer(
  {
    schema,
    // 👇
    onNext: (ctx, _msg, _args, result) => {
      if (result.errors) {
        // if there are errors, format the mand return the altered result
        result.errors = yourErrorFormatter(ctx, result.errors);
        return result;
      }
      // otherwise do nothing
    },
  },
  new WebSocketServer({ port: 4000 }),
);
```

**Comment by asadhazara** [comment]
Okay, thank you @enisdenjo for the quick replies!

**Comment by intellix** [comment]
also came here wondering the same thing. I've currently got a plugin which loops through errors and logs errors and I'm also using formatError from ApolloServer to send things to Sentry, so naturally I saw this hook and added the same logic there.

Was surprised to see that it's not called on my errors even though it says in the description that it can be used for formatting errors:  
<img width="799" alt="Screenshot 2022-08-25 at 18 49 11" src="https://user-images.githubusercontent.com/1162531/186734620-d8b8b226-2f07-42d0-8103-7c72f9ee5702.png">

I still don't understand what that means if it doesn't get called on any error

**Comment by enisdenjo** [comment]
GraphQL has 2 types of errors:
- Parsing / validation errors: errors that happen **before** the GraphQL operation - they're surfaced in the [`onError` hook](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.ServerOptions.md#onerror)
- Execution errors: errors that happen in resolvers **during** the GraphQL operation - they're surfaced in the [`onNext` hook](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.ServerOptions.md#onnext)

  For example: if you make a GraphQL request: `{ a, b }` and only `b` resolver errors out, the execution **happened** but partially succeeded. The result will therefore be `{ data: { a: 'I am a', b: null }, errors: [{ message: 'Something happened with b' }] }`.
