### ISSUE TITLE
Using `graphql-ws` with redis pubsub causes `TypeError`

### ISSUE THREAD

**Issue by EizFeren** [enisdenjo/graphql-ws#293]
**Description**
I've got `TypeError` while trying to use redis pubsub instead of in-memory pubsub for apollo graphql subscriptions

**Screenshot**
Error output
![Error](https://user-images.githubusercontent.com/63458616/148055745-ddc72bd2-3927-4d7e-abd2-3f129afad43f.png)

51-53 lines from `lib/utils.mjs`
![image](https://user-images.githubusercontent.com/63458616/148053426-1399dbfa-4ad2-4a59-b88b-7de4097df970.png)

**Expected Behaviour**
Expected to working correctly with redis pubsub

**Actual Behaviour**
Got `TypeError: Cannot read property 'length' of undefined`. I've added logging for `reason` in function from screenshot above, and `reason` is `undefined` with redis pubsub

**Debug Information**
`graphql-ws` version - ^5.5.0
`graphql-redis-subscriptions` version - ^2.4.2
`apollo-server` version - ^3.1.2
NodeJS version - v14.17.6
Redis version - v6.0.6

**Comment by enisdenjo** [comment]
The `reason` there is the WebSocket close event reason message. There should always be one, at least an empty string (but not `undefined`). 

Can you tell me more about your WebSocket server and how it's set up?

**Comment by EizFeren** [comment]
I've debugged call of `limitCloseReason` in `node_modules/graphql-ws/lib/use/ws.mjs` (86 line), and got my subscription's payload instead of error

![image](https://user-images.githubusercontent.com/63458616/148060221-54d124f6-b873-47e8-ba0a-d15d5a0b5b21.png)

(`err` is subscription's payload here)

About server - this is common Apollo graphql server with webosckets
![image](https://user-images.githubusercontent.com/63458616/148061401-458113ef-a4cf-4c9c-9f61-598ed9b3da9e.png)

**Comment by EizFeren** [comment]
Redis pubsub setup

![image](https://user-images.githubusercontent.com/63458616/148062203-85ffb2f2-ad63-4301-b951-0eb973714590.png)

**Comment by enisdenjo** [comment]
`err` is subscription payload? Why is a subscription payload being thrown? 

Can you share the payload and also follow the callstack to the original thrower (ideally share the whole callstack too)?

**Comment by EizFeren** [comment]
Maybe reason is in callback handling - as I saw by adding logs to `graphql-ws/lib/use/ws.mjs` (79 line),  `onMessage` event receives a Buffer values - but redis pubsub provides an object

Initiation of subscription
![image](https://user-images.githubusercontent.com/63458616/148083436-1d107829-c39a-4964-aa79-2247561ef76e.png)

Subscription resolver
![image](https://user-images.githubusercontent.com/63458616/148083537-7a9771a8-67ec-4d03-b42f-ed51253a8637.png)

Original thrower `graphql-ws/lib/use/ws.mjs` 86 line, `onMessage` event, tracing below
![image](https://user-images.githubusercontent.com/63458616/148082818-e27b173c-acf6-4193-80cd-fcccec417bd6.png)

Error message below
![image](https://user-images.githubusercontent.com/63458616/148083171-39d0cc78-c43e-4ad3-ad75-0be2cc286556.png)

**Comment by EizFeren** [comment]
Maybe this is redis pubsub issue, I'll check this too

**Comment by enisdenjo** [comment]
`graphql-ws` is not the original thrower here. The library itself has very few throw statements and they're either handled internally or ultra obvious in explaining how to fix. Regardless, everything that `graphql-ws` would throw is an instance of an Error - and what your catching is an object.

Something else is throwing here, as stated in the last screenshot's log "Please check your implementation.". Sadly, I am not familiar with redis so I cannot even hint on "what?". But, if you take a look at the last screenshot, you can see is an object matching your first screenshot's second argument (`{ promotionSet: { value: { test: 'test' } } }`).

P.S. please don't post code screenshots. You cannot select any text, it is very hard to read and hard to reference. Instead, simply copy and paste.

**Comment by EizFeren** [comment]
I've debugged much more, and finally got reason of the issue - `graphql-redis-subscriptions` can't use `node-redis` v4 client. It works fine after replacing `node-redis` to `ioredis` client.

It's very strange about throwing at this module, and I'm sorry for missunderstanding.

**Comment by enisdenjo** [comment]
That's fine, glad you figured it out!
