### ISSUE TITLE
Link to apollo-server-express integration is incorrect

### ISSUE THREAD

**Issue by Narretz** [enisdenjo/graphql-ws#302]
In the readme, there's a link 

https://github.com/enisdenjo/graphql-ws/blob/1b9fc26653c203508de530883ec4c28aa02ab678/README.md?plain=1#L1046

to this page: https://github.com/apollographql/apollo-server/tree/main/packages/apollo-server-express

which as far as I can see has nothing to do with graphql-ws. The package is not in the package.json and the code doesn't touch subscriptions at all.

**Comment by enisdenjo** [comment]
I don't understand. Have you read the recipe?

**Comment by Narretz** [comment]
Oh I see. I was confused by the expandability of the docs. Because some detail expanders additionally contain external links, I followed the link and didn't see anything about graphql-ws.
