### ISSUE TITLE
Typescript error in Relay example

### ISSUE THREAD

**Issue by dkolbly** [enisdenjo/graphql-ws#316]
Trying to follow the example of using `graphql-ws` with Relay from the README, I get a typescript error.

**Screenshot**
![image](https://user-images.githubusercontent.com/1017053/155033385-a210f135-a05a-4b86-a227-8d6a4d9ab4e5.png)
**Expected Behaviour**
I expected the example code to compile.

**Actual Behaviour**
but instead it has a type error.

**Debug Information**
I also tried lifting the type to the declaration of `fetchOrSubscribe`, in which case the error appears on `sink`:
![image](https://user-images.githubusercontent.com/1017053/155033881-77e567ef-2854-4457-92d1-b9b81d7df5e2.png)

Here is the text of the original type error:

```
Argument of type '(operation: RequestParameters, variables: Variables) => RelayObservable<unknown>' is not assignable to parameter of type 'SubscribeFunction'.
  Type 'RelayObservable<unknown>' is not assignable to type 'RelayObservable<GraphQLResponse> | Disposable'.
    Type 'RelayObservable<unknown>' is not assignable to type 'RelayObservable<GraphQLResponse>'.
      Type 'unknown' is not assignable to type 'GraphQLResponse'.
        Type 'unknown' is not assignable to type 'readonly GraphQLSingularResponse[]'.ts(2345)
```

**Further Information**
```
    "relay-runtime": "^13.1.1",
    "graphql-ws": "^5.6.0",
```

**Comment by dkolbly** [comment]
PS I just saw there was a new version of `graphql-ws` published, so I tried `5.6.1` with the same result.

**Comment by enisdenjo** [comment]
Seems like there's a disagreement between `relay-runtime` and `graphql` about how the execution result should look like. [`relay-runtime`'s execution result `data` field **cannot be** `null`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/fb785106d6264285d452e2e7efb5c68c0639fbd8/types/relay-runtime/lib/network/RelayNetworkTypes.d.ts#L43) vs. [`graphql`'s execution result `data` field **can be** `null`](https://github.com/graphql/graphql-js/blob/da5723860e87c97831c02a1137e9431d96c14239/src/execution/execute.ts#L132)

Additionally, Relay seems to separate the exec. result in 3 parts: `GraphQLResponseWithData`, `GraphQLResponseWithoutData` and `GraphQLResponseWithExtensionsOnly`. And the union of them additionally doesn't accept the `graphql` exec. result `errors` field.

Weird... I'll go ahead and read the GraphQL spec itself and decide about the next steps.

In the meantime, you can leverage the `any` type to make the result fit:
```diff
- function fetchOrSubscribe(operation: RequestParameters, variables: Variables) {
+ function fetchOrSubscribe(operation: RequestParameters, variables: Variables): Observable<any> {
```

**Comment by enisdenjo** [comment]
Sadly, seems like there's no union satisfying both sides (`relay-runtime` and `graphql`).

With that in mind, I'll proceed with supporting `graphql`, simply because it's the _official_ JavaScript reference implementation for GraphQL.

**Comment by dkolbly** [comment]
Thanks for the unblocker!  Bummer that relay-runtime and graphql disagree in such a simple yet type-breaking way.

**Comment by fersilva16** [comment]
I've found a way to fix this issue without using `any`:

```ts
import { createClient, type Sink } from 'graphql-ws';
import {
  type GraphQLResponse,
  Observable,
  type RequestParameters,
  type Variables,
} from 'relay-runtime';
import { config } from '../lib/config';

const client = createClient({
  url: config.GRAPHQL_SUBSCRIPTION_URL,
});

export const subscribeFn = (
  operation: RequestParameters,
  variables: Variables,
) => {
  return Observable.create<GraphQLResponse>((sink) => {
    if (!operation.text) {
      return sink.error(new Error('Operation text cannot be empty'));
    }

    return client.subscribe(
      {
        operationName: operation.name,
        query: operation.text,
        variables,
      },
      sink as Sink,
    );
  });
};
```
