### ISSUE TITLE
Updating README for easier Apollo support

### ISSUE THREAD

**Issue by glasser** [enisdenjo/graphql-ws#325]
Hi @enisdenjo! We at Apollo appreciate that you took the initiative to create a better-maintained alternative to `subscriptions-transport-ws`. Over the past few months we've pushed to ensure that all parts of the Apollo platform that support subscriptions can work with `graphql-ws`. We've now hit that point, so we've officially deprecated and archived `subscriptions-transport-ws`.

There's a few places where we can update your README to help people use `graphql-ws` with Apollo software. I'm happy to file a PR but I'm curious which of these changes you'd be interested in.

- Apollo Client Web: There's a code snippet already showing how to define a custom "link" for use with Apollo Client Web. We've adapted that code and it now ships as part of `@apollo/client` as of v3.5.10.  I would like to document that explicitly in your README.  Do you think I should just entirely replace the existing section, or keep the existing section around as a second section specifically for users who haven't upgraded yet?
- Apollo iOS and Apollo Kotlin: These projects have built-in opt-in support for `graphql-ws`. Would new sections showing how to set them up be appreciated?
- Apollo Server: We have a fuller example in our docs that is a bit improved in a few ways. It properly drains the subscription server at shutdown, and it makes sure to call `useServer` before `app.listen` instead of after. Would it make more sense for me to improve the example in the README to look more like the example in our docs (https://www.apollographql.com/docs/apollo-server/data/subscriptions/#enabling-subscriptions), or add a link to our docs to the existing example, or even replace the example with the doc list?
- Apollo Studio Explorer: This web UI (kind of like GraphiQL/GraphQL Playground) supports `graphql-ws` now, though you have to explicitly select it in a settings panel. Would mentioning this be appreciated in the README?

**Comment by enisdenjo** [comment]
Wow, I am more than humbled you've devoted such a huge effort into migrating parts of Apollo, thanks for putting your trust in `graphql-ws`!

As far as the readme goes, feel free to push PRs for everything you find suitable that uses `graphql-ws`, the more the merrier - as long as it fits neatly inside the [Recipes](https://github.com/enisdenjo/graphql-ws#recipes) and keeps the style of other recipes (recipe titles are easy to understand and find, no talking - just code, if documentation is necessary - use comments, copy-paste-able, links are very welcome).

**Comment by martinbonnin** [comment]
Re: Apollo iOS and Apollo Kotlin, they're compatible with `graphql-ws`, the protocol (https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md), but not with `graphql-ws`, the Typescript library. It feels a bit weird to have them next to the other recipes. Should I create a "Compatible libraries" section or something like this?

**Comment by enisdenjo** [comment]
I want to avoid overgrowing the README, I think `graphql-ws` is quite simple to use.

IMHO I think it's just fine having it in recipes. Title it "Client usage with Apollo iOS" and when the accordion is expanded, there's a short description "uses protocol blah blah graphql-ws can be on backend blah blah" and a link to the actual documentation supporting the programming language in question.

**Comment by glasser** [comment]
Fixed in #328, #335, and #334.
