### ISSUE TITLE
Clients can't connect to socket server

### ISSUE THREAD

**Issue by ragokan** [enisdenjo/graphql-ws#346]
**Screenshot**
GraphiQL
![image](https://user-images.githubusercontent.com/63511519/161830143-7ffabd58-7264-4b2f-b6fe-0a0af2868099.png)
uRQL Client - Console
![image](https://user-images.githubusercontent.com/63511519/161830153-fdbff60d-53b1-4ae5-b300-5834dd6faa47.png)

**Expected Behaviour**
I expected it to do connect the socket server.

**Actual Behaviour**
but instead it did give me error without any response.

**Setup**
For server, I am using ExpressJS with GraphQL-Helix/Envelop

```ts
// initial setup with cookies, form data etc.
const server = app.listen(PORT, () => {
    const wsServer = new WebSocketServer({
      path: "/graphql",
      server,
    });

const { execute, subscribe } = getEnveloped({});

useServer(
      {
        execute,
        subscribe,
        onError: writeError,
        onSubscribe: async (ctx, msg) => {
              // this is never called
              // on error is also never called (it is only a logger)
```

In the error message in console above, the *response* is undefined. I also tried doing it noServer:true, still I got the same error.

**Comment by enisdenjo** [comment]
And what client are your using? I am guessing the [deprecated `subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws). If so, please read [the disclaimer in the readme](https://github.com/enisdenjo/graphql-ws#disclaimer).

**Comment by ragokan** [comment]
> And what client are your using? I am guessing the [deprecated `subscriptions-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws). If so, please read [the disclaimer in the readme](https://github.com/enisdenjo/graphql-ws#disclaimer).

Hello, I am using *graphql-ws* as client with uRQL.
```ts
import { createClient as createWSClient } from "graphql-ws";
const wsClient = createWSClient({ url: "myUrl" });
```

**Comment by enisdenjo** [comment]
Ok weird. This error looks like theres a problem with the network, can you confirm you're using the right URL on the clients (and that the server is available)? Is the server on the same local network? Can you provide me a screenshot of the WebSocket request from your browsers DevTools?

I would greatly appreciate a repro too, thanks!

**Comment by ragokan** [comment]
> Ok weird. This error looks like theres a problem with the network, can you confirm you're using the right URL on the clients (and that the server is available)? Is the server on the same local network? Can you provide me a screenshot of the WebSocket request from your browsers DevTools?
> 
> I would greatly appreciate a repro too, thanks!

Well, I actually think it is something to do with the server. I just tried to run it without NodeJS manager of CWP (it is actually deployed currently), so I run it in SSH and it actually worked but I got this error;

```ts
Internal error occurred during message handling. Please check your implementation. TypeError: Cannot read properties of undefined (reading 'definitions')
```
Weirdly everything else is working fine, let me search about it, fix it and try it again.

**Comment by enisdenjo** [comment]
Hmm, never seen that error before, seems like it's coming from `graphql-js` raised [here](https://github.com/enisdenjo/graphql-ws/blob/f7aadc2569d6b20f1f65d64d83fdd90c50b32fb2/src/server.ts#L763-L766).

Are you providing the proper GQL schema to the server?

**Comment by enisdenjo** [comment]
Also, I see you're using [`envelop`](https://github.com/dotansimha/envelop), there's a [proper implementation example in their repo](https://github.com/dotansimha/envelop/blob/main/examples/graphql-ws/index.ts).

**Comment by ragokan** [comment]
> Also, I see you're using [`envelop`](https://github.com/dotansimha/envelop), there's a [proper implementation example in their repo](https://github.com/dotansimha/envelop/blob/main/examples/graphql-ws/index.ts), could that be the culprit?



> Hmm, never seen that error before, seems like it's coming from `graphql-js` raised [here](https://github.com/enisdenjo/graphql-ws/blob/f7aadc2569d6b20f1f65d64d83fdd90c50b32fb2/src/server.ts#L763-L766).
> 
> Are you providing the proper GQL schema to the server?

Hey, I did all of them correctly, it actually now working fine locally, yet when I deploy it to Heroku, it gave me the error;

```ts
2022-04-06T13:59:52.591376+00:00 app[web.1]: Internal error occurred during message handling. Please check your implementation. TypeError: Cannot read properties of undefined (reading 'definitions')
2022-04-06T13:59:52.591383+00:00 app[web.1]: at getOperationAST (/app/node_modules/graphql/utilities/getOperationAST.js:18:40)
2022-04-06T13:59:52.591384+00:00 app[web.1]: at onMessage (/app/node_modules/graphql-ws/lib/server.js:172:76)
2022-04-06T13:59:52.591385+00:00 app[web.1]: at processTicksAndRejections (node:internal/process/task_queues:96:5)
2022-04-06T13:59:52.591385+00:00 app[web.1]: at async WebSocket.<anonymous> (/app/node_modules/graphql-ws/lib/use/ws.js:83:21)
```

But in docs of GraphiQL, actually everything looks fine;
![image](https://user-images.githubusercontent.com/63511519/161992874-76f2017d-d627-4913-938b-4b4527717e3c.png)

**Comment by ragokan** [comment]
Well, let me close the issue for now because it is probably something to do with Heroku or my code, if anybody else got the same error, can always write here. 

@enisdenjo Thank you so much for helping that fast.
