### ISSUE TITLE
invalid message received from server

### ISSUE THREAD

**Issue by sherif-cyber** [enisdenjo/graphql-ws#347]
thank you in advance, any help please ?
### connection established successfully to server but when subscribed always received **"Invalid message"**

"error": Event {
    "code": **4004**,
    "isTrusted": false,
    "reason": **"Invalid message"**,
  },

### server using **uWebSockets.js**v20.6.0
- support both **subscriptions-transport-ws** & **graphql-ws**.
- "@apollo/client": "3.3.14",

### client using graphql-ws-5.6.4
- "@apollo/client": "^3.5.10",

**Comment by enisdenjo** [comment]
Can you share the invalid message received? 

What do you mean by the server supporting both libs? In case you're using the deprecated `subscriptions-transport-ws`, please read the [disclaimer in the readme](https://github.com/enisdenjo/graphql-ws#disclaimer).

**Comment by sherif-cyber** [comment]
### thanks that's mis configuration from our side 

problem because that i wasn't follow that [server.ts](https://github.com/enisdenjo/graphql-ws/blob/master/src/server.ts) correctly...
