### ISSUE TITLE
Protocol needs a SubscriptionAck message

### ISSUE THREAD

**Issue by andreasdamm** [enisdenjo/graphql-ws#364]
### Story

As a client I want to have a positive acknowledgement for a subscription.

Currently, the only responses to a subscription are error or complete. There is no way to ascertain when the subscription requested has actually been processed in the success case.

Knowing when a subscription has been made successfully is important in processing flows where executing the next step is dependent on a subscription being made.

In our example, a device discovery process on the network can only be initiated once it is known for certain the the subscription is in place. Otherwise discovery messages being delivered through the subscription can be lost.

### Acceptance criteria

The client can await a confirmation that a subscription has been made successfully so that subsequent processing dependent on receiving subscription messages can be initiated.

**Comment by enisdenjo** [comment]
Very interesting point you're making. Was thinking whether having an init event coming from GraphQL itself on subscribe could solve the issue - but I am afraid not - it would make subscriptions more complex and queries/mutations couldn't possibly support this.

I will invest some thinking about how to implement this in a non-breaking and backwards compatible matter as an optional, opt-in, feature for the server.

Thanks for bringing this up!

**Comment by theogravity** [comment]
We actually have this same issue where the client thinks it's ready to receive events, but it's really that the socket is just connected.

We had to do the following hack to inform the client to not do anything until the subscription is fully set up:

```
        onOperation: async (ctx) => {
          // We want to signal that the client is now ready for events before continuing
          // We can't send out any kind of message as graphql-ws is sensitive to the type being sent out
          // So we send out ack + payload as pong supports a custom payload
          // https://github.com/enisdenjo/graphql-ws/blob/d47e1bb5ff5589bf49587e70b446a2cab01688d1/src/common.ts#L222
          ctx.extra.socket.send(
            JSON.stringify({ type: MessageType.ConnectionAck, payload: { result: 'subscription_ready' } }),
          );
        },
``` 

Then on our client, we have a custom callback we call when we get the event from the server that it can then proceed with it's init process

```
onConnected: (socket) => {
        // The backend connection takes time to warm up so we need to
        // wait for a message to know the client is fully ready to get
        // events before continuing via the onOperation call on backend
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        const parseMessage = (event: any) => {
          const data = JSON.parse(event.data);
          if (data?.payload?.result === 'subscription_ready') {
            connected();
            socket.removeEventListener('message', parseMessage);
          }
        };

        socket.addEventListener('message', parseMessage);
}
```

**Comment by eduardocque** [comment]
+1

**Comment by enisdenjo** [comment]
@andreasdamm @theogravity @eduardocque 

Sorry for the wait, I wanted to invest a proper thought.

While thinking about the `SubscriptionAck` and its use-case, I've realised that this message is yet another "pinger" notifying the receiver about something. Having said this, the [`Ping` message +  payload](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md#ping) is actually a perfect fit.

Leveraging the ping message and existing server/client options, a subscription acknowledgment extension would look like this:
```ts
// 🛸 server

import { WebSocketServer } from 'ws';
// import ws from 'ws'; yarn add ws@7
// const WebSocketServer = ws.Server;
import { MessageType, stringifyMessage } from 'graphql-ws';
import { useServer } from 'graphql-ws/lib/use/ws';
import { schema } from './my-graphql-schema';

const wsServer = new WebSocketServer({
  port: 4000,
  path: '/graphql',
});

useServer<undefined, { ackWaiters: Record<string, () => void> }>(
  {
    schema,
    onConnect: (ctx) => {
      // listeners waiting for operation acknowledgment. if subscription, this means the graphql.subscribe was successful
      // intentionally in context extra to avoid memory leaks when clients disconnect
      ctx.extra.ackWaiters = {};
    },
    onSubscribe: (ctx, msg) => {
      const ackId = msg.payload.extensions?.ackId;
      if (typeof ackId === 'string') {
        // if acknowledgment ID is present, create an acknowledger that will be executed when operation succeeds
        ctx.extra.ackWaiters![msg.id] = () => {
          ctx.extra.socket.send(
            stringifyMessage({
              type: MessageType.Ping,
              payload: {
                ackId,
              },
            }),
          );
        };
      }
    },
    onOperation: (ctx, msg) => {
      // acknowledge operation success and remove waiter
      ctx.extra.ackWaiters![msg.id]?.();
      delete ctx.extra.ackWaiters![msg.id];
    },
  },
  wsServer,
);

console.log('Listening to port 4000');
```
```ts
// 📺 client

import {
  Client,
  ClientOptions,
  createClient,
  ExecutionResult,
  Sink,
  SubscribePayload,
} from 'graphql-ws';

// client with augmented subscribe method accepting the `onAck` callback for operation acknowledgement
type ClientWithSubscribeAck = Omit<Client, 'subscribe'> & {
  subscribe<Data = Record<string, unknown>, Extensions = unknown>(
    payload: SubscribePayload,
    sink: Sink<ExecutionResult<Data, Extensions>>,
    onAck: () => void,
  ): () => void;
};

function createClientWithSubscribeAck(options: ClientOptions): ClientWithSubscribeAck {
  const client = createClient(options);

  const ackListeners: Record<string, () => void> = {};
  client.on('ping', (_received, payload) => {
    const ackId = payload?.ackId;
    if (typeof ackId === 'string') {
      ackListeners[ackId]?.();
      delete ackListeners[ackId];
    }
  });

  return {
    ...client,
    subscribe: (payload, sink, onAck) => {
      const ackId = Math.random().toString(); // be wary of uniqueness
      ackListeners[ackId] = onAck;
      return client.subscribe(
        {
          ...payload,
          extensions: {
            ...payload.extensions,
            ackId,
          },
        },
        sink,
      );
    },
  };
}
```

Using the augmented client would be as simple as:
```ts
const client = createClientWithSubscribeAck({
  url: 'ws://i.want.ack:4000/graphql',
});

(async () => {
  const onNext = () => {
    /* handle incoming values */
  };

  let unsubscribe = () => {
    /* complete the subscription */
  };

  let subscriptionAcknowledged = () => {
    /* server successfully subscribed */
  };

  await new Promise((resolve, reject) => {
    unsubscribe = client.subscribe(
      {
        query: 'subscription { greetings }',
      },
      {
        next: onNext,
        error: reject,
        complete: resolve,
      },
      subscriptionAcknowledged,
    );
  });

  expect(subscriptionAcknowledged).toBeCalledFirst();

  expect(onNext).then.toBeCalledTimes(5); // we say "Hi" in 5 languages
})();
```

**Comment by 6uliver** [comment]
I found this issues since I faced the same problem and I also need to have an acknowledge for the subscriptions. I think `SubscribeAck` should be introduced as a response for the `Subscribe`. My specific use case is that I bind a queue to a RabbitMQ exchange when I have a new subscription and this operation is obviously async so I need to wait it to be sure that my AsyncIterator is ready and won't miss any messages from that point: it means that the subscription is completely ready.

Your proposal to implement it with `Ping` can work but:

1. it requires additional custom development
2. it's more verbose than necessary since the protocol requires that for every `Ping` the other side must send a `Pong` as a response. So the flow would be:

C->S `Subscribe`
S->C `Ping` to signal successful subscription
C->S `Pong` to signal acknowledgement for the acknowledgement of the successful subscription

I think the ideal protocol would be to have a standardized acknowledgement for the subscription:

C->S `Subscribe`
S->C `SubscribeAck` to signal successful subscription

For backward compatibility: I think it can not break anything since no one was used the `SubscribeAck` message type before.

Ideal format and the description of the message following the current protocol's conventions:

**SubscribeAck**
Direction: Server -> Client

The server has initialized the subscription for the operation identified by <unique-operation-id>. After this point the client won't miss any messages published for that subscription.

```
interface SubscribeAckMessage {
  id: '<unique-operation-id>';
  type: 'subscribe_ack';
}
```

What do you think?

**Comment by 6uliver** [comment]
@enisdenjo any thoughts?
