### ISSUE TITLE
Uncaught/Unhandled promise rejection from close event error after subscribing client

### ISSUE THREAD

**Issue by imolorhe** [enisdenjo/graphql-ws#365]
The `denied()` (`Promise.reject`) call on [this line](https://github.dev/enisdenjo/graphql-ws/blob/9d5c5733ba8bb181ef4f2051da958d80786c9ee6/src/client.ts#L652) which gets called on close or if there is an error is not handled, or at least not always handled.

A simple way to reproduce it is to create a client and subscribe to a non-existent websocket endpoint. The `on.error()` handler gets called correctly with the error but the `denied()` in the code still gets called which triggers a `Promise.reject` that needs to be "caught" or handled somehow, but the only handle to the promise (`connecting`) was [unassigned](https://github.dev/enisdenjo/graphql-ws/blob/9d5c5733ba8bb181ef4f2051da958d80786c9ee6/src/client.ts#L649) already so the promise cannot be handled.

**Expected Behaviour**
I don't expect there to be a trailing unhandled promise rejection when there is a close event error.

**Actual Behaviour**
Instead I get an uncaught promise rejection error when `denied(errOrEvent)` is called because, nothing is handling the promise rejection.

**Debug Information**
I believe the reason why this issue is very problematic for me is because my app is based on angular based on zone.js which handles these unhandled promise rejections differently, and it gets bubbled up to my global error handler. I could decide to filter and ignore uncaught promise rejection errors but this looks like an issue that should not be there in the first place.

**Comment by enisdenjo** [comment]
Are you maybe running the client in non-lazy mode? If so, you should provide the [`onNonLazyError` option](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/client.ClientOptions.md#onnonlazyerror) to catch errors thrown before any subscribers become available.

**Comment by enisdenjo** [comment]
Can you please share your exact client configuration? Preferably also the errors you're getting and their callstacks.

**Comment by imolorhe** [comment]
I tried creating a repro in stackblitz but so far I have not been able to. I'll close this issue for now and try to see why this uncaught rejection only affects my application.

Btw out of curiosity, is the promise rejection handled? Or it's not handled but that is fine for some reason?
