### ISSUE TITLE
It would be helpful if Error: Invalid message included more information

### ISSUE THREAD

**Issue by jeffreyyoung** [enisdenjo/graphql-ws#366]
### Story

As a server, when I send a client an invalid message, the client surfaces the following error: `Error: Invalid message`.  From the error message it is difficult to debug what exactly went wrong.  I would like it if the error message included more information on why the message was invalid, e.g. Message must be parseable json | message.type must be defined | message.payload cannot be null

### Acceptance criteria
 `Error: Invalid message` error is more descriptive

**Comment by enisdenjo** [comment]
Makes sense, let me see what I can do.

Thanks for bringing this up!
