### ISSUE TITLE
Use @fastify/websocket instead of fastify-websocket

### ISSUE THREAD

**Issue by kingston** [enisdenjo/graphql-ws#381]
Right now, the example for Fastify integration and typing depend on fastify-websocket. However, fastify-websocket has been deprecated (https://www.npmjs.com/package/fastify-websocket) as it has been renamed to @fastify/websocket. Do you know if it would be possible to update the typings to use @fastify/websocket instead of fastify-websocket?

Happy to submit a PR if this would be considered worthwhile.

**Comment by enisdenjo** [comment]
Definitely makes sense!

I've noticed that the semantics changed too, I'll investigate accordingly and roll out a proper integration; thanks for bringing it up!
