### ISSUE TITLE
Many consecutive short operations cause high chance of lazyCloseTimeout triggering close

### ISSUE THREAD

**Issue by Momics** [enisdenjo/graphql-ws#388]
**Screenshot**
![image](https://user-images.githubusercontent.com/12343163/185407942-8944ab08-85ef-4eb0-8b7b-10445adeb20b.png)

(Schematic timeline of what's happening, the blocks are operations and the arrows are the lazyCloseTimeout's set by the release fn)

**Expected Behaviour**
I expected lazyCloseTimeout to be 're-scheduled' every time a subscription releases it's lock, so that the connection is left open until lazyCloseTimeout ms of inactivity.

**Actual Behaviour**
Instead, each completed subscription schedules it's own timeout. With many short successive subscriptions (completing fast) and some network irregularity chances are high there are 0 locks when the timeout triggers. In the image, just before the last subscription is about to trigger, the connection is closed abruptly.

Especially in the case of short lived subscriptions (e.g. when you are doing mutations over ws only), it adds a lot of unnecessary websocket handshakes.

**Debug Information**
What I did myself to fix it, is to clear any open lazyCloseTimer(s) before scheduling a new one, essentially 'debouncing' the operation until there is no further activity left:

See this code for reference: https://github.com/enisdenjo/graphql-ws/blob/master/src/client.ts#L790-L797

I declared a lazyCloseTimer before the connect function in the client and then changed above code to:

```ts
// Clear any other lazy close timers
clearTimeout(lazyCloseTimer);
// Then set a new one, essentially debouncing the complete check
lazyCloseTimer = setTimeout(() => {
  // (With the old code, there is a high chance locks = 0 here)
  if (!locks && socket.readyState === WebSocketImpl.OPEN)
    complete();
}, lazyCloseTimeout);
```

**Further Information**
It could be that I am interpreting the intended behaviour of lazyCloseTimeout in the wrong way.

**Comment by Momics** [comment]
I don't really know how to write a test for this either. I discovered the behaviour using the following setup on the client side. I adapted it to work with the example server from the README:

```ts
import { createClient } from 'graphql-ws';

const client = createClient({
  url: 'ws://localhost:4000/graphql',
  lazyCloseTimeout: 1000,
});

const totalQueries = 100;
let currentCount = 0;
let t = setInterval(async () => {
  if (currentCount > totalQueries) {
    clearInterval(t);
    return;
  }

  client.subscribe(
    { query: `{ hello }` },
    {
      next: (data) => {
        //
      },
      complete: () => {
        currentCount++;
        console.log("Done", currentCount);
      },
      error: (err) => {
        console.log(err);
      },
    }
  );
}, 100);
```

Running this on a client in the browser allows you to at least easily spot/experiment with the behaviour:

![image](https://user-images.githubusercontent.com/12343163/185617882-851a52f5-d2ad-4996-ac34-65ca76b14445.png)

As you can see from the 'time' column, sometimes the close happens exactly after 1 second (no locks). Sometimes it misses the opening and it then triggers just 100ms or 200ms later.

**Comment by enisdenjo** [comment]
Awesome stuff, your example inspired my test case:

https://github.com/enisdenjo/graphql-ws/blob/c332837c50da09174a9741a1903a5471f8a1c42d/src/__tests__/client.ts#L1396-L1429

It was indeed failing before the fix in https://github.com/enisdenjo/graphql-ws/commit/c332837c50da09174a9741a1903a5471f8a1c42d.

Thank you @Momics for this great discovery!
