### ISSUE TITLE
Creating a new subscription is very CPU intensive

### ISSUE THREAD

**Issue by mezykr** [enisdenjo/graphql-ws#396]
**Screenshot**
![grafana](https://user-images.githubusercontent.com/3213836/189368513-00620006-4df3-4975-9e9a-ac37c0aab85f.png)

**Expected Behaviour**
On client side I have simple form with numeric inputs. Basing on values entered to those fields I want to compute the value on backend and then send the result to client by using subscription. After 500ms debounce for values entered into fields, I'm setting them as subscription variables (@apollo/client -> useSubscription()) what causes current subscription complete and new subscription subscribe. This approach is working fine and fast for small number of concurrent users filling the form with values.

**Actual Behaviour**
I've created simple boilerplate project to demonstrate my setup:
[https://github.com/mezykr/graphql-ws-perf](https://github.com/mezykr/graphql-ws-perf)

I'm running load test to simulate 300 - 700 concurrent users filling the values to the form in below scenario for each user:
1. open ws connection
2. change subscription variable (type: subscribe)
3. wait 500ms
4. change subscription variable (type: complete/subscribe)
3. wait 500ms
4. change subscription variable (type: complete/subscribe)
5. .... doing above points in the loop for 5minutes
6. closing ws connection

In above scenario I'm getting results as on attached screenshot
300 Users - ~30% CPU
500 Users - ~50% CPU
700 Users - ~70% CPU

**Debug Information**
I'm using simple subscription in my example which has two numbers in variables and returns their sum as result. In my example I'm using PubSub async iterator to simulate some update on subscription every 200ms but removing it does not change/improve performance at all. What I've noticed the most expensive process is creating a new subscription - we don't even need to send any data from resolver. 

**Further Information**
When I've implemented simple cache mechanism for parsing/validating process during subscribe (inside graphql-ws package) the results were only ~5% better

**Comment by enisdenjo** [comment]
Interesting, thanks for reporting this. I will take a look at your repro and report back! BTW, I've just pushed a small performance optimization with https://github.com/enisdenjo/graphql-ws/commit/d44c6f18ccd2bc539bb541e6bfd1bf0c769c7856 that could make a difference.

**Comment by mezykr** [comment]
@enisdenjo Thanks for the response. Good job on removing try/catch from there - typeof data usually is a string there so throwing an error/catching was not the best solution.

Unfortunately I don't think it will make significant difference for CPU usage... I'm on a middle of investigation what can be improved - would you be open for PR with my changes?

**Comment by enisdenjo** [comment]
Yeah, the try/catch shouldn't be making a big difference.

PRs are very welcome! I will also dig into your repro today and see what can be discovered. Thanks!

**Comment by mezykr** [comment]
@enisdenjo Hey, I've just created PR with my changes: https://github.com/enisdenjo/graphql-ws/pull/400

I've added simple in-memory cache implementation for parse/validate process. This is optional and as default is disabled. I've measured CPU usage before my change and after by running my test with 500 concurrent users - with cache CPU usage is 2x less.

![Screen Shot 2022-09-14 at 9 53 13](https://user-images.githubusercontent.com/3213836/190131907-50ab16d6-1af6-4db1-97b7-51647240b13a.png)

**Comment by enisdenjo** [comment]
Hey thanks for #400, but as mentioned in https://github.com/enisdenjo/graphql-ws/pull/400#issuecomment-1248508109, a cache is something that can, and should, be implemented in user-land.

I've profiled the server using [my benchmarks](https://github.com/enisdenjo/graphql-ws/tree/master/benchmark) and the results are just a-ok. Most of the time was spent in `graphql.validate` and none of graphql-ws internals were heavy or slow.

Possible optimizations here seem to be only around [graphql-js](https://github.com/graphql/graphql-js), one of them being a cache.

I am closing this issue as the optimizations fall out of graphql-ws scope. If you discover performance issues affecting graphql-ws core, feel free to re-open this one or create a new issue! Thanks!
