### ISSUE TITLE
Not working with Chrome

### ISSUE THREAD

**Issue by alebeta90** [enisdenjo/graphql-ws#410]
Dear all,

Recently we decided to move out the deprecated package `subscriptions-transport-ws` to this `graphql-ws`.
We found a "very interesting" issue where our websocket client works perfectly with clients using Firefox and Safari, but not with Chrome(tested in OSX, Linux and Windows).

Something interesting is when running the backend websocket server locally with ws instead of wss it works. The problem occurred only with Chrome connecting to our AWS Serverless environment.

I believe the implementation in our code should be fine since it is working with Firefox and Safari, but we are open with any suggestion or lead to debug further this behavior. 

**Screenshot**
This is what we can see from the console log.
![image](https://user-images.githubusercontent.com/11571266/195426899-cfac0f1c-5559-4995-9fc7-9065325977a8.png)

And this is the status of the request, it seems the request got timeout, there is not response from our api gateway at all
![image](https://user-images.githubusercontent.com/11571266/195428327-421e3587-82cc-45a4-863f-c3cb209e7591.png)

If we have a look at the request from Firefox, there are different headers in place. It is interesting it has the `Accept` header which is missing in Chrome request

![image](https://user-images.githubusercontent.com/11571266/195428695-b3a76994-dfe3-4775-9219-407a0d6968a2.png)

**Expected Behaviour**
I expected it to work in Chrome as well.

**Actual Behaviour**
but instead it did not work in chrome :(

thanks in advance

**Comment by enisdenjo** [comment]
Hmm, weird. And you say the exact same code works for Firefox and Safari? 🤔

Would be of great help if you could provide me with a repro repository, or simply with a URL where I can try connecting and debugging myself. Thanks in advance!

**Comment by alebeta90** [comment]
Hi @enisdenjo ,

thanks for your reply. I had been working and researching on this issue, and actually you did answer before about the error 1006. And it was because we were using a lib for ws in the backend which is not compatible with graphql-ws. Now we do not get the error after moving to graphql-lambda-subscriptions.

Thanks for your message!
