### ISSUE TITLE
Websocket event "connection_ack" with "payload" as null result into closed connection

### ISSUE THREAD

**Issue by guilhermeavanci** [enisdenjo/graphql-ws#450]
**Screenshot**
![image](https://user-images.githubusercontent.com/6515575/221256761-a06343ad-898d-4795-99e4-3bfa963fbf79.png)

**Expected Behaviour**
I expected it to treat `null` as a valid value to be received through the `payload` property, or at least not throw an error in this case.

**Actual Behaviour**
Right now if the server for some reason returns the `payload` as `null` the following error is thrown:
`"connection_ack" message expects the 'payload' property to be an object or missing, but got "null"`

This error stops the connection and prevents the websocket from being used.

**Debug Information**
This is the [commit](https://github.com/enisdenjo/graphql-ws/commit/b46379e5946b8ce10e907588399350b8ba256c4c#diff-1f963b5ae3613de37b5354a3da594cdef878e0715ad0eb3896bd701e2511b273R232) where the error throw was added.

Before that, **apparently**, this situation wasn't an issue simply because it doesn't stop the websocket connection, right!? (Not sure about that)

I tried to use both `jsonMessageReviver` and `jsonMessageReplacer` to intercept the `payload` and turn it into `undefined` to prevent the error throw, but I had no success. Is there a way to do that?

**Further Information**
Sadly I can't change the backend right now for other reasons.

Thank you very much in advance for the help!

**Comment by enisdenjo** [comment]
The idea was to completely omit the field if it does not exist, decreasing the message size. But, I don't see why we couldn't make it nullable.

I will take care of this, thanks for writing!

**Comment by guilhermeavanci** [comment]
I agree! Decreasing message size is definitely the better approach. Sadly we can't change this on the backend right now, we're using another third-party library there, which also has been [informed about the "null issue"](https://github.com/ExpediaGroup/graphql-kotlin/issues/1685). It's a corner case between both libraries.

Thank you very much for the quick response! We're going to wait for the fix!

**Comment by enisdenjo** [comment]
Closed and released with #456.
