### ISSUE TITLE
graphql-transport-ws rejection specification

### ISSUE THREAD

**Issue by kristjanvalur** [enisdenjo/graphql-ws#455]
### Story

As a _server implementor_ I want to have a standard way to be able to **positively reject** a connection when I receive a `connection_init` message, 
so that a _client_, upon receiving that message, can know that it has been rejected, and receive some message
to that effect.

### Acceptance criteria

- _server_ is able to send a _standard_ response in response to `connection_init` indicating a rejected connection and the reason for this, followed by closing the websocket connection.
- _client_ can wait for either the usual `connection_ack`, or this new standard response, before attempting a `subscribe` message
- The protocol specification _specifies_ how to reject a connection upon receiving `connection_ack`.

### Discussion

Currently the only _in protocol_ way to not accept a connection is by _not sending_ a `connection_ack` message.  However, this is not a _positive rejection_ and a _client_ cannot know for how long he should be waiting for the `connection_ack` message.  Further, there is no way to convey a _reason_, such as "rejected", "busy", "unauthorized", etc.

Simply closing the websocket is not ideal, since that is a separate protocol layer.

### Suggestion

- We could add an _optional_ field to `connection_ack`, `success:bool`, defaulting to  `true`, but with a `false` value indicating reject.
- We could permit an `error` message to be sent at this point.  However, `error` messages are related to individual _operations_ and have an `operation-id`.  Further, their cargo is a `GraphQLError` list, which is not what this error is specifying.
- We could specify that the standard way is to close the _websocket_ with some specific error code.

**Comment by enisdenjo** [comment]
> Simply closing the websocket is not ideal, since that is a separate protocol layer.

Why not? This is the reason why there is no positive rejection. You have an abundance of user-land close codes (4000-4999) that can be accompanied with any 123 character reason.

Furthermore, you can close the connection at any time (even after acknowledging the connection, or before even considering the connection) and it is very convenient to do so within `graphql-ws` hooks.

> We could specify that the standard way is to close the websocket with some specific error code.

The standard _is_ to close the connection with a close event. GraphQL over WebSocket is a subprotocol under WebSockets, meaning - the conventions of WebSockets are recommended and implied. The spec should be kept as light as possible, it should aim to standardise the GraphQL relevant transport with enough constraints but very small overhead.

**Comment by kristjanvalur** [comment]
Okay, still user-land error codes are always ambiguous.  When writing an implementation conforming to a protocol and expecting good interoperability, it is great to have rules and recommendations and as little ambiguity as possible.

Could we agree on a websocket close code in this case?  Would you accept a PR where this recommendation on how to reject a `connection_init` request is made explicit?

**Comment by enisdenjo** [comment]
Sure, a recommendation sounds good. But please make it `4403: Forbidden` instead because that is what the library uses if you [return false in the `onConnect` hook](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.ServerOptions.md#onconnect):

https://github.com/enisdenjo/graphql-ws/blob/972ed07ea263624bb556970cfd85bb05ea2c6eac/src/server.ts#L614

**Comment by enisdenjo** [comment]
My bad, I referenced the wrong issue when merging #456.

**Comment by kristjanvalur** [comment]
Ok, created a PR.  There is code out there written in different programming languages which is trying to follow the spec, and not necessarily reverse engineering the .ts source :)
