### ISSUE TITLE
"realTimeConsumptionEnabled": false

### ISSUE THREAD

**Issue by TylonHH** [enisdenjo/graphql-ws#468]
Hello,
I'm not sure where to place my problem. Suddenly my real Time Consumption stopt working over API.
I tried to regenerate a new API Token.
I disconnected the Pulse from the App and connected again.
Within the App I see the Live Data, there is eveything fine.
But I dont see them anymore on the https://developer.tibber.com/explorer

How I know?
Get Home-ID
```
{
  viewer {
    homes {
      id
    }
  }
}
```
then put this into this query
```
{
  viewer {
    home(id: "YOURHOMEID") {
      id
      features {
        realTimeConsumptionEnabled
      }
    }
  }
}
```
then I got this
`"realTimeConsumptionEnabled": false`

How can I enable this? Why is this off?

**Comment by enisdenjo** [comment]
Your question has nothing to do with graphql-ws itself.
