### ISSUE TITLE
Publish a browser specific bundle for the client

### ISSUE THREAD

**Issue by OmgImAlexis** [enisdenjo/graphql-ws#47]
Any chance on a browser specific bundle being added to the build process so that it's easy to use with services like unpkg?

**Comment by enisdenjo** [comment]
The library leverages [the `browser` field in package.json](https://docs.npmjs.com/cli/v6/configuring-npm/package-json#browser) to communicate the entrypoint for a browser environment.
https://github.com/enisdenjo/graphql-ws/blob/3f5c42e3deb7d014258417d20df29ef9e1fb1ed7/package.json#L25

If you look this lib up on unpkg following their URL structure: https://unpkg.com/graphql-ws@1.10.0 - you'll get the browser code exclusively.

**Comment by OmgImAlexis** [comment]
That’s not the issue. The file still has “exports” meaning it can’t be used via a script tag.

**Comment by enisdenjo** [comment]
Ah, now I follow, you're interested in an AMD or UMD build. This makes sense!

I'll see what I can do and will keep you posted 👍.

**Comment by sibelius** [comment]
I think rollup could help on this one

**Comment by enisdenjo** [comment]
Heads up! As of [v1.11.0](https://github.com/enisdenjo/graphql-ws/releases/tag/v1.11.0), you can:
```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>GraphQL over WebSocket</title>
    <script
      type="text/javascript"
      src="https://unpkg.com/graphql-ws/umd/graphql-ws.min.js"
    ></script>
  </head>
  <body>
    <script type="text/javascript">
      (function () {
        const client = graphqlWs.createClient({
          url: 'wss://umdfor.the/win/graphql',
        });

        // consider other recipes for usage inspiration
      })();
    </script>
  </body>
</html>
```
_* Plucked straight out of [the lib recipes](https://github.com/enisdenjo/graphql-ws#recipes)_

**Comment by OmgImAlexis** [comment]
Not sure it needs the IIFE but yay. 🙌
