### ISSUE TITLE
Docs folder is missing

### ISSUE THREAD

**Issue by matthewninja** [enisdenjo/graphql-ws#470]
**Screenshot**
![Screen Shot 2023-04-04 at 4 27 48 PM](https://user-images.githubusercontent.com/14874215/229912658-b34d4bcd-218d-4c09-8a1d-6ea18c2db68b.png)

**Expected Behaviour**
If the docs folder was moved to guild.dev, links should be updated to point to the new location.

**Actual Behaviour**
The docs folder 404s.

**Further Information**
Many places in the official Apollo Client docs link to this repositories docs. For instance, this page: https://www.apollographql.com/docs/react/api/link/apollo-link-subscriptions/

Even the README on this repository under ## Documentation links to `website/src/pages/docs`

**Comment by enisdenjo** [comment]
Ooh great catch! I've updated the readme with https://github.com/enisdenjo/graphql-ws/commit/6d163b0ef016169c20e33006a2ea01f266c349b1 and made a PR for Apollo's client documentation https://github.com/apollographql/apollo-client/pull/10727.

Thanks for reporting!
