### ISSUE TITLE
Npm and tsc build fails on 5.13.0 due to bun-types

### ISSUE THREAD

**Issue by antego** [enisdenjo/graphql-ws#478]
**Expected Behaviour**
Build started by `tsc -b tsconfig.json` passes

**Actual Behaviour**
Build fails with the error
```
node_modules/graphql-ws/lib/use/ws.d.ts:1:23 - error TS2688: Cannot find type definition file for 'bun-types'.

1 /// <reference types="bun-types" />
```

**Debug Information**
Failing version is 5.13.0

**Further Information**
Revert to version 5.12.1 fixes the problem

**Comment by enisdenjo** [comment]
Oooh, seems like TS build added the triple-slash directive to all declaration files - even though its only in the [use/bun.ts](https://github.com/enisdenjo/graphql-ws/blob/master/src/use/bun.ts). Sorry about that, fix incoming!
