### ISSUE TITLE
graphql-yoga integration example breaks for mutations

### ISSUE THREAD

**Issue by RMHonor** [enisdenjo/graphql-ws#480]
**Overview**

When integrating our existing websocket server into graphql-yoga, we used the [example recipe for integration](https://the-guild.dev/graphql/ws/recipes#ws-server-usage-with-graphql-yoga), which wraps the request with envelop. This forwards the request object from the initial connection, which is a GET request, and so the usePreventMutationViaGET kicks in and prevents any mutation operations over the websocket.

**Expected Behaviour**
Mutations should be possible across the websocket.

**Actual Behaviour**
Mutations fail with an HTTP error 405 (method not allowed).

**Debug Information**
Example stack:
```
GraphQLError: Can only perform a mutation operation from a POST request.    
  at createGraphQLError (/Users/richardhonor/uw/crm-graphql/node_modules/graphql-yoga/node_modules/@graphql-tools/utils/cjs/errors.js:9:12)    
  at assertMutationViaGet (/Users/richardhonor/uw/crm-graphql/node_modules/graphql-yoga/cjs/plugins/requestValidation/usePreventMutationViaGET.js:21:46)    
  at /Users/richardhonor/uw/crm-graphql/node_modules/graphql-yoga/cjs/plugins/requestValidation/usePreventMutationViaGET.js:57:17    
  at /Users/richardhonor/uw/crm-graphql/node_modules/@envelop/core/cjs/orchestrator.js:110:17    
  at onSubscribe (/Users/richardhonor/uw/crm-graphql/src/main.ts:106:27)    
  at onMessage (/Users/richardhonor/uw/crm-graphql/node_modules/graphql-ws/lib/server.js:147:124)    
  at WebSocket.<anonymous> (/Users/richardhonor/uw/crm-graphql/src/websocket.ts:149:21)    
  at WebSocket.emit (node:events:513:28)    
  at WebSocket.emit (node:domain:489:12)    
  at Receiver.receiverOnMessage (/Users/richardhonor/uw/crm-graphql/node_modules/ws/lib/websocket.js:1180:20)
```

**Further Information**
As a workaround, I modified the request object so all operations are passed through as a POST:

```typescript
useServer(
  {
    execute: (args: any) => args.rootValue.execute(args),
    subscribe: (args: any) => args.rootValue.subscribe(args),
    onSubscribe: async (ctx, msg) => {
      const { schema, execute, subscribe, contextFactory, parse, validate } =
        yoga.getEnveloped({
          ...ctx,
          req: {
            ...ctx.extra.request,
            method: "POST",
          },
          socket: ctx.extra.socket,
          params: msg.payload,
        });
 
      const args = {
        schema,
        operationName: msg.payload.operationName,
        document: parse(msg.payload.query),
        variableValues: msg.payload.variables,
        contextValue: await contextFactory(),
        rootValue: {
          execute,
          subscribe,
        },
      };
 
      const errors = validate(args.schema, args.document);
      if (errors.length) return errors;
      return args;
    },
  },
  wsServer,
);
```

Related previous issue: https://github.com/dotansimha/graphql-yoga/issues/1704

**Comment by enisdenjo** [comment]
Hmm, which version of Yoga are you using? Can you create a repro because the example recipe works for me?

Furthermore, there's a [graphql-ws example in Yoga](https://github.com/dotansimha/graphql-yoga/blob/7ea9777/examples/graphql-ws/src/app.ts) with tests, and one of them [ensures mutations work](https://github.com/dotansimha/graphql-yoga/blob/474d5571df6c49235dacd692b12b024b7f2d4f30/examples/graphql-ws/__integration-tests__/graphql-ws.spec.ts#L36-L57).
