### ISSUE TITLE
fix incorrect Bad Gateway error code

### ISSUE THREAD

**Issue by thumbsupep** [enisdenjo/graphql-ws#510]
https://github.com/enisdenjo/graphql-ws/blob/4f4ac19c526a0bc7f013e3dadc298ef98758f3be/src/client.ts#L1082-L1097

**Expected Behaviour**
`1014` is used for Bad Gateway so that Bad Gateway is not treated as a fatal error.

**Actual Behaviour**
`1013` is considered both `Try Again Later` and `Bad Gateway` so Bad Gateway errors are incorrectly classified as fatal.

**Further Information**
Websocket connection close code for Bad Gateway should be `1014` https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent/code#value

This will be a breaking change because there might be consumers who need to update error handling to prevent a change in behavior for the `1014` close code.

I would love to contribute this change, but could only find documentation on opening an issue, not creating a PR.

**Comment by enisdenjo** [comment]
Great find! PR is more than welcome. However, I don't think this will be a breaking change.

**Comment by enisdenjo** [comment]
Closed with #512.
