### ISSUE TITLE
Warning Workspaces can only be enabled in private projects.

### ISSUE THREAD

**Issue by jer-sen** [enisdenjo/graphql-ws#524]
You should remove this from `package.json` to avoid this warning when installing the module:

```
  "workspaces": [
    "website"
  ],
```

**Comment by enisdenjo** [comment]
Thanks for pointing this out @jer-sen! The new release [v5.14.3](https://github.com/enisdenjo/graphql-ws/releases/tag/v5.14.3) doesn't include the `workspaces` entry, try it out.

**Comment by jer-sen** [comment]
@enisdenjo you're welcome!
