### ISSUE TITLE
Some subscriptions remain open after a websocket has been closed

### ISSUE THREAD

**Issue by andreasdamm-shure** [enisdenjo/graphql-ws#532]
**Expected Behaviour**
When a client closes a websocket then all subscriptions (i.e. async iterables) on the server side need to have their `return` method called (if defined) regardless of whether the client sent an unsubscribe message before closing the websocket.

**Actual Behaviour**
Some subscriptions remain open on the server after the websocket has been closed.

**Debug Information**
When a subscription request is received, the asynchronous `subscribe` resolver of the executable schema is ultimately called. https://github.com/enisdenjo/graphql-ws/blob/e2603be5788e51fc5ce5649a508f2649ee6adb27/src/server.ts#L797 

Once the returned promise is resolved a subscription entry is made in `ctx.subscriptions`. https://github.com/enisdenjo/graphql-ws/blob/e2603be5788e51fc5ce5649a508f2649ee6adb27/src/server.ts#L812

If the promise is resolved after the websocket close handler has been called the an entry is still made in `ctx.subscriptions` and its `return` method will never be called. 

Depending on the subscription object leakage of memory and resources can ensue.

**Further Information**
Here is an example program: [post-close-subscription-bug.zip](https://github.com/enisdenjo/graphql-ws/files/14225423/post-close-subscription-bug.zip)

Run `yarn install` followed by `yarn start` and open a browser window for http://localhost:4000/graphql. Start a subscription in that window :--

```graphql
subscription {
  never
}
```

then close the browser window (without stopping the subscription first) within less than five seconds of establishing the subscription.

Open another browser window for http://localhost:4000/graphql and run

```graphql
query {
  count
}
```

A count of 1 should be returned.

Repeating the same process but waiting at least five seconds before closing the subscription browser window should not lead to an increase of the count.

**Comment by enisdenjo** [comment]
Wow great catch! I've managed to create a failing test replicating what you've described. Thanks for reporting it! Fix coming soon.
