### ISSUE TITLE
Clients can be sent an `Error` message after cancellation.

### ISSUE THREAD

**Issue by divanise** [enisdenjo/graphql-ws#539]
From examining the code handling the `Subscribe` message, it looks like it is possible for a custom async `onOperation` callback or `schema` function to delay long enough for a client to cancel the subscription before either returns. If that happens *and* an error occurs before the subscription starts, the server will still send an `Error` message for that stream.

One obvious fix is to include a [`notifyClient` parameter to the `error`](https://github.com/lazarentertainment/graphql-ws/commit/369c486f58c17a206ae96e205dfc2844b5c9d676) function on the emit object, to match how the `complete` function works.

**Comment by enisdenjo** [comment]
Each of the handler implementation in `use/*` have a check whether the socket is open before sending any messages. Nevertheless, I've added a fix in the server itself as well. It's released in [v5.16.0](https://github.com/enisdenjo/graphql-ws/releases/tag/v5.16.0).
