### ISSUE TITLE
Make code and reason optional when closing a connection

### ISSUE THREAD

**Issue by tobiasdiez** [enisdenjo/graphql-ws#547]
Small thing, but 
https://github.com/enisdenjo/graphql-ws/blob/6013eb54829b27bd7c598f0985ec80a0e1acf09c/src/server.ts#L420
requires a `code` and `reason`, while the [specs](https://www.rfc-editor.org/rfc/rfc6455.html#section-7.4) say that the status code is optional ("MAY indicate a reason").

**Comment by enisdenjo** [comment]
Conventionally you'd always specify the two. Also, you I want the users to always be clear and explicit about their closes. However, I have no hard reason to keep the two required - would you be interested in opening a PR? 😄
