### ISSUE TITLE
Optional payload in ConnectionAck

### ISSUE THREAD

**Issue by Amareis** [enisdenjo/graphql-ws#59]
### Story

As a server developer I want to pass some connection context to client (for example - current session registration step).

So that client can get it without additional requests.

### Acceptance criteria

- server is able to pass payload in `ConnectionAck` message (return object in onConnect instead of true?).
- client is able to handle it properly (pass it in on connected event?).

In subscription-transport-ws it's mentioned in docs, but not implemented in code.

**Comment by enisdenjo** [comment]
Hey, thanks for opening this issue - I think this makes a lot of sense!

I'll see what I can do. 👍

**Comment by Amareis** [comment]
Oh, big thanks for such fast fix! We really will transfer from subscriptions-transport-ws on next week.
