### ISSUE TITLE
µWebSockets

### ISSUE THREAD

**Issue by kevinwei00** [enisdenjo/graphql-ws#61]
Haven't properly evaluated this library yet, but was wondering if you have taken a look at https://github.com/uNetworking/uWebSockets.js ?

**Comment by enisdenjo** [comment]
Hey hey, thanks for opening this issue!

Honestly, I've never heard of µWebSockets 😅. It looks great in terms of performance, but, following the brief glance I had - thats where the features end haha.

I'd love to know more, can you elaborate a bit on the pros and cons of this library? Why, except for the performance boost, do you choose [µWebSockets](https://github.com/uNetworking/uWebSockets.js) over [ws](https://github.com/websockets/ws)?

Furthermore, it would be possible for the `server` library to take in a custom WebSocket implementation. [Something like the `client` does.](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/_client_.clientoptions.md#websocketimpl) The only requirement for the implementation would be having the same interface as [ws](https://github.com/websockets/ws).

**Comment by enisdenjo** [comment]
I stumbled across [a Medium article called: "Beware of uWebsockets.js!"](https://medium.com/@rockstudillo/beware-of-uwebsockets-js-b51c92cac83f). It pushed very important problems about the library, mainly the author. TBH, I don't like what I've read...

-  > _(about the author)_ ... Insults and the like are the norm in his way of treating people, and ultimately he will ban you or delete complete issues if they are exposing any flaws in his library or how he behaves.

    We might not know what we _must_ know! Deleting issues because of disagreements or flaws which you dont want to patch is hella scary. (There is even a link to a issue in the article which is deleted...)
-

**Comment by enisdenjo** [comment]
I stumbled across [a Medium article called: "Beware of uWebsockets.js!"](https://medium.com/@rockstudillo/beware-of-uwebsockets-js-b51c92cac83f). It pushed very important problems about the library, mainly the author. TBH, I don't like what I've read...

-  > _(about the author)_ ... Insults and the like are the norm in his way of treating people, and ultimately he will ban you or delete complete issues if they are exposing any flaws in his library or how he behaves.

    We might not know what we _must_ know! Deleting issues because of disagreements or flaws which you dont want to patch is hella scary. (There is even a link to a issue in the article which is deleted...)
- > it must be pointed out that this is not installing the package from the NPM registry, but from the private github repository of the package’s author.
    >
    > The main implications of this is that, **1) the repository can be deleted at any time** (not very unlikely considering past events), and **2) the tag pointing to a version can be changed to point to a different commit** (not very unlikely either since this was the reason for the original dispute with uWS).

    `graphql-ws` (and its Protocol) treats security as the first-class citizen, so this is a deal breaker for me. I will not promote unsafe libraries with this repo. Package immutability is _THE_ thing that keeps us, JavaScript devs, safe.
- > The author provides precompiled binaries, which, while being convenient for some users and platforms has the added risk of not knowing if the binaries really correspond to the source code or a specific version of the source code.

   No additional comment necessary.

_Performance_ or _Security_? I'll choose security any time of the day.

_P.S._ I still wouldn't mind allowing a custom WebSocket implementation for the `server`. Of course, with the requirement of it being an [ws](https://github.com/websockets/ws) server compatible interface.

**Comment by kevinwei00** [comment]
@enisdenjo Thanks for the detailed response! And one that other devs must know about as well. I was really just scanning its performance claims 😅 .

**Comment by enisdenjo** [comment]
Of course! Thank YOU though, with this issue we have learned something new about the world. 😄

**Comment by ivarsg** [comment]
@enisdenjo, @kevinwei00 and other devs, I think it is worth to read also [Alex Hultman's (author of µWebSockets) thoughts](https://medium.com/@alexhultman/beware-of-tin-foil-hattery-f738b620468c) on the above mentioned Manuel Astudillo's article. There are always two sides of the medal, two truths of the opposite opinions :)

**Comment by enisdenjo** [comment]
Awesome! Thanks for sharing the post, there sure are two sides of every story. 😅

**Comment by evenfrost** [comment]
Honestly speaking, I think this response is childish and insulting itself, and only proves Manuel's assumptions on the library author.

**Comment by enisdenjo** [comment]
Manual had good points, Alex had too - but this is just grownups being childish.

Alex literally gained nothing by following his moral compass and ditching the forever growing, community trusted, npm; because "he finds their Terms of Service repulsive, from a purely legal standpoint". He now has to (and will probably have to forever) hold [a link to "A note on speculations, lies & allegations" in the main readme of the lib](https://github.com/uNetworking/uWebSockets.js). And even with this, Google being Google - I managed to stumble across Manuel's article first. xD

Not only this, but to feel safe (since you cant _just_ rely on Git tags) - you have to fork, make sure you have the tools to build the lib, build it, package it, deploy it manually to all your services; instead of just doing `yarn add uws`. He basically twisted all our hands; I, personally, would end up avoiding the lib simply because of the hassle, whatever the performance gains are...

Furthermore, he DID delete that issue. Whatever the reason, he did it. We now can only trust his word that it was actually what he said it was.

**Comment by maxpain** [comment]
I've done integration [here](https://github.com/enisdenjo/graphql-ws/pull/89)

**Comment by enisdenjo** [comment]
@kevinwei00 good news, the integration has landed with [v4.4.0](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.4.0). Would be awesome if you could try it out, given free time. 😄
