### ISSUE TITLE
Socket is closed even though there are pending subscriptions

### ISSUE THREAD

**Issue by rpastro** [enisdenjo/graphql-ws#66]
I'm using graphql-ws together with Apollo client. 

I noticed that for queries and mutations the cancellerRef.current is being invoked twice. Once when the Complete message is received and again from the cleanup function.

As a result state.locks gets decremented twice for the same operation, which causes the socket to be closed even though there are pending operations.

**Comment by enisdenjo** [comment]
Hmm, are you sure? I reckon this test would be failing then because of the double decrement: https://github.com/enisdenjo/graphql-ws/blob/3f4f836c395139617a268082131084c4f992ba5f/src/tests/client.ts#L500-L537
Maybe the test is flawed? 🤔

**Comment by rpastro** [comment]
The problems happens with queries and mutations where the server sends the Completed event.  What I noticed, at least with Apollo, is that the cleanup function gets invoked almost at the same time which causes the cancellerRef.current to be called twice for the same subscription.

**Comment by rpastro** [comment]
BTW, this is the cleanup function I'm referring to.

```
      return () => {
        cancellerRef.current?.();
      };
```

**Comment by enisdenjo** [comment]
Ah, I follow. I was thinking about the canceller cleanup, the one _in_ it haha. 

Nevertheless, you're right, it can sure happen. I'll head over to your PR. 😄
