### ISSUE TITLE
Keep socket alive for a configured time

### ISSUE THREAD

**Issue by rpastro** [enisdenjo/graphql-ws#68]
Currently, if the ClientOption lazy is true, the websocket is closed as soon as there are no pending operations.

This adds a lot of overhead in case you have an application that is often sending queries or mutations since the client needs to re-establish the socket for every query/mutation.

It would be great if we could add a new `keepalive` parameter to ClientOptions that would control how long the socket should remain open after the last subscription has completed.

For instance:

```
export interface ClientOptions {
...
  /**
   * How long the client should wait, after the last query/mutation/subscription is completed, before closing the socket.
   *
   * @default 0 * 1000 (0 seconds)
   */
  keepalive?: number;
...
}
```

**Comment by rpastro** [comment]
@enisdenjo  I would be willing to work on this improvement if you would like.

**Comment by enisdenjo** [comment]
I think this is an unnecessary complexity. Exactly because of the overhead, we allow setting `lazy` to `false` to persist the connection. 😄 

If you want even the fine grained control you're suggesting - I would actually prefer building one on top of the library. Where you recycle the client (`client.dispose` + `client = createClient`) however you find comfortable.

**Comment by sibelius** [comment]
what about a Recipe for this?

**Comment by rpastro** [comment]
There are two problems with setting lazy to false.

The first one is that the client tries to create the WS before our application has obtained the security token which is required for the ConnectionInit message.

The second issue is that the goal is not to create a WS that stays open the entire time.  The goal is to avoid closing & immediately reopening the socket within a few milliseconds.   I still want to close the WS if there is no new activity after a certain amount of time.

**Comment by rpastro** [comment]
> The first one is that the client tries to create the WS before our application has obtained the security token which is required for the ConnectionInit message.

Regarding this. Another enhancement I would like to suggest is to accept `connectionParams` to be a Promise or async function.   I can open a separate enhancement request for this if you agree.

**Comment by enisdenjo** [comment]
A recipe would be a way, however... I spoke too soon.

@rpastro has actually a great point! I changed my mind, this would be indeed nice to have. Am already cooking up some code for this - bare with me. 😄

**Comment by enisdenjo** [comment]
> Another enhancement I would like to suggest is to accept connectionParams to be a Promise or async function. I can open a separate enhancement request for this if you agree.

I agree! Please open another issue just for the sake of clarity and documentation.
