### ISSUE TITLE
Allow connectionParams to be Promise or async function

### ISSUE THREAD

**Issue by rpastro** [enisdenjo/graphql-ws#70]
Currently the connectionParams option must be either a Record<string, unknown> or a synchronous function that returns Record<string, unknown>.

```
  /**
   * Optional parameters, passed through the `payload` field with the `ConnectionInit` message,
   * that the client specifies when establishing a connection with the server. You can use this
   * for securely passing arguments for authentication.
   */
  connectionParams?: Record<string, unknown> | (() => Record<string, unknown>);
```

This is an issue for applications that need to asynchronously retrieve the data for the ConnectionInit message. Like for instance retrieving a security token required for the WS authentication.  This is particularly a problem in case `lazy` option is set to false and the client tries to open the WS immediately.

This is enhancement request to allow connectionParams to be either a Promise or async function, so the application can asynchronously retrieve the information required for the `ConnectionInit` message.

**Comment by enisdenjo** [comment]
Awesome! Makes total sense. PR incoming...

**Comment by rpastro** [comment]
@enisdenjo  When are you planning to release a new version of graphql-ws which includes the enhancements merged today?

**Comment by enisdenjo** [comment]
As soon as I close this issue.
