### ISSUE TITLE
Cannot stringify invalid message; isMessage validation for execution result is too strict

### ISSUE THREAD

**Issue by n1ru4l** [enisdenjo/graphql-ws#72]
A stream payload published by an AsyncIterable returned by `execute` (from `graphql@15.4.0-experimental-stream-defer.1`) cannot be stringified

```
{
  id: '7aef51de-707e-49e5-8cbf-df1bff572e5f',
  type: 'next',
  payload: { data: 'Friend', path: [ 'streamTest', 2 ], hasNext: true }
}
```

It fails silently with the following message, I had to dig into node_modules and add a bunch of console.logs before I had access to this message.

```
Error: Cannot stringify invalid message
    at Object.stringifyMessage (/Users/laurin/projects/stream-defer-demo/node_modules/graphql-ws/cjs/message.js:87:15)
```

It would be nice if such an error would not be swallowed by default but instead forwarded to the console. The user could then overwrite the default behavior.

Aside from that, this message object (returned from execute) should be accepted as a valid message. I don't understand why exactly the message sent by the server must be validated - as the server constructs it should be fine? Also, the current validation seems to be rather inflexible and must be updated every time graphql supports a new execution result variation. The responsibility for returning a correct result should be within execute.

Reference code:

```graphql
type Query {
  greetings: [String]
}
```

```graphql
query StreamTestQuery {
  streamTest @stream(initialCount: 1)
}
```

```ts
const Query = new GraphQLObjectType({
  name: "Query",
  fields: {
    streamTest: {
      type: GraphQLList(GraphQLString),
      resolve: async function* () {
        for (const item of ["Hi", "My", "Friend"]) {
          yield item;
          await sleep(1000);
        }
      },
    },
})
```

**Comment by enisdenjo** [comment]
Nothing should be failing silently. Are you sure the socket is not closed with the error in the close event reason? Keep in mind that the client will retry a few times if the connection gets closed (you might not see the error immediately).

If its indeed failing silently, please make a test or a repro and I will be more than happy to look at it and bring up a fix! (Please make an additional issue)

Furthermore, the server validates messages because they should follow the Protocol's shapes. I'd say the validation for the `next` message is very forgiving - it requires the `data` or the `errors` field to be an object in the `payload`:
https://github.com/enisdenjo/graphql-ws/blob/0d2f9745469c9e3bde3a35d26041ceb11dd0283e/src/message.ts#L120-L127
Message you provided is failing because the `data` field is a string. How does a query that gives you just a string in the data object look like? (just curious 😄)

It does make sense to support _whatever_ for the `data` field - fix is coming!

**Comment by n1ru4l** [comment]
The example above shows such a query, with the schema and Query Object type 😅

You are right, the client connection gets closed and it will retry connecting. However, since this is a error in general related to the server, I would actually also expect to see that issue logged to the console.

**Comment by enisdenjo** [comment]
You can hook up onto [the `closed` event](https://github.com/enisdenjo/graphql-ws/blob/master/docs/modules/_client_.md#eventclosed) for the client and log all socket closes.

I check just the basics, [the simplest form of `graphql-js`'s `ExecuteResult`](https://github.com/graphql/graphql-js/blob/dec555409043e04c8d5949386e12e544ad33ef56/src/execution/execute.d.ts#L42-L59) (any `data` or object `errors`). The message has a super simple form, so it should be rather easy to detect why the message is malformed - hence vague error.

I plan on making the client retry connections on some errors only - classify the fatal ones and report them immediately.

Furthermore, all of server-side error handling issues will go away as soon as #64 lands. You will have full control of error handling and reporting then. Once this lands, tracking if the malformed issue originates from the back or front should be easy. Will keep your insights in mind though!

**Comment by n1ru4l** [comment]
defer and stream AsyncIterables returned from execute will emit a final `{ hasNext: false }` JSON payload. See src/execution/__tests__/stream-test.js here: https://github.com/graphql/graphql-js/commit/dec555409043e04c8d5949386e12e544ad33ef56#diff-a370dc23e95e90e2b04fe67a3a933e6eb09296c64b4eae7509cd3ae93edaf2ae

**Comment by enisdenjo** [comment]
Oh! Well, thats enough for me. I'll just make it so that the validation makes sure that the `payload` is present. You can pass _whatever_ you want.

**Comment by enisdenjo** [comment]
There, [you can now pass whatever you want for the payload](https://github.com/enisdenjo/graphql-ws/commit/7cebbfe00dc3c360e80e8962f345a28743b49c1f). 😄

**Comment by n1ru4l** [comment]
Awesome 👏 Thanks for considering this!

**Comment by enisdenjo** [comment]
Thank you for bringing it up!

**Comment by enisdenjo** [comment]
BTW, [the client now fails immediately for some fatal close event codes](https://github.com/enisdenjo/graphql-ws/commit/4d9134b8704446f0b2674c71e25d7c6c44000c9a). This should improve the DX by bringing a problem up sooner.
