### ISSUE TITLE
Support async Context function

### ISSUE THREAD

**Issue by Jonahss** [enisdenjo/graphql-ws#74]
### Story

When a subscription comes in, I'd like to set the `context` that the resolver receives.
This can be done using the `context` option of createServer.
Right now, whatever is returned by this function is passed as the context to all resolvers.
I'd like the option to return a Promise, and have the returned value be awaited upon, so that all my resolvers don't need to await the context.

**Comment by enisdenjo** [comment]
Fair enough! Enhancement coming in.
