### ISSUE TITLE
Usage with Relay

### ISSUE THREAD

**Issue by slaviczavik** [enisdenjo/graphql-ws#76]
Hello,

I'm trying to figure it out how to make this work with Relay. According to Relay [docs](https://relay.dev/docs/en/subscriptions#configure-network) a subscribe function has to return an observable. 

When I write this function:
```js
const subscribe = (request, variables) => {
  const subscribeObservable = subscribeClient.subscribe({
    query: request.text,
    operationName: request.name,
    variables,
  })

  // Important: Convert subscriptions-transport-ws observable type to Relay's
  return Observable.from(subscribeObservable);
}
```

It just doesn't works, because RelayNetwork returns error: _No data returned for operation_.

On other hand, when I use subscription-transport-ws it just works.

**Comment by sibelius** [comment]
do you wanna migrate this on Relay Workshop (https://github.com/sibelius/relay-workshop/issues/13)

check recipes for the right usage with relay

it is like this

```jsx
import { createClient } from 'graphql-ws';

const subscriptionsClient = createClient({
  url: config.GRAPHQL_SUBSCRIPTION_URL,
});

export const subscribeFn = (
  operation: RequestParameters,
  variables: Variables,
) => {
  return Observable.create((sink) => {
    if (!operation.text) {
      return sink.error(new Error('Operation text cannot be empty'));
    }
    return subscriptionsClient.subscribe(
      {
        operationName: operation.name,
        query: operation.text,
        variables,
      },
      {
        ...sink,
        error: (err) => {
          if (err instanceof Error) {
            sink.error(err);
          } else if (err instanceof CloseEvent) {
            sink.error(
              new Error(
                `Socket closed with event ${err.code}` + err.reason
                  ? `: ${err.reason}` // reason will be available on clean closes
                  : '',
              ),
            );
          } else {
            // GraphQLError[]
            sink.error(new Error(err.map(({ message }) => message).join(', ')));
          }
        },
      },
    );
  });
};
```

**Comment by enisdenjo** [comment]
There is a [Client usage with Relay recipe in the readme](https://github.com/enisdenjo/graphql-ws#recipes), check it out! 😄

**Comment by slaviczavik** [comment]
> There is a [Client usage with Relay recipe in the readme](https://github.com/enisdenjo/graphql-ws#recipes), check it out! 😄

Oh, I'm so sorry, I didn't realize it's clickable text, I always cliked on the Relay link 😅

**Comment by enisdenjo** [comment]
No worries! Glad we could help.

**Comment by enisdenjo** [comment]
Hey @slaviczavik, if you are satisfied with the answers - please close this issue. 😁
