### ISSUE TITLE
Add ConnectionNack message to protocol

### ISSUE THREAD

**Issue by Kingdutch** [enisdenjo/graphql-ws#78]
### Story

As a developer I want a message type so that I can inform clients of the reason for the denial of their connection request.

As a client I want to know why my ConnectionInit request was not accepted so that I can fix the issue (e.g. prompt user for auth data) rather than have the connection suddenly close.

### Acceptance criteria

- A developer is able to inform the client why a connection request was denied (for example invalid authentication data)

**Comment by Kingdutch** [comment]
I realised this can be treated as an "Invalid Message"

**Comment by enisdenjo** [comment]
I think you might find #75 interesting! 😄

**Comment by Kingdutch** [comment]
I saw that and it is interesting, but that doesn't stretch to PHP unfortunately ;-) 

I'm working on a PHP implementation for the protocol based on Ratchet so sending custom stuff is already easy. I just want to make sure it sticks to the defined protocol so that GraphQL clients using this transport layer can talk to it :)

**Comment by enisdenjo** [comment]
Absolutely lovely to hear! 😄

In general, I try to be as close as possible to the pure necessities of GraphQL with the Protocol. You should be able to handle auth, and other GraphQL unrelated topics, how ever you see fit.
