### ISSUE TITLE
Subscription with Hasura Server

### ISSUE THREAD

**Issue by VietKhangLH** [enisdenjo/graphql-ws#79]
**Actual Behaviour**

Hello,

I have the error :
WebSocket connection to 'the url' failed: Error during WebSocket handshake: 'Sec-WebSocket-Protocol' header value 'graphql-ws' in response does not match any of sent values

**Debug Information**
I work with Hasura on Heroku.
I just interface graphql-ws with Apollo with your code.

**Further Information**
Everything was working with ws client from Apollo.
But I had to change because of security issues that your kind work strive to resolve.

**Comment by enisdenjo** [comment]
You are not communicating with this library. Our sub-protocol is `graphql-transport-ws`.

You are communicating with `subscriptions-transport-ws`, their sub-protocol is`graphql-ws`.

Make sure that you use this library (or implement the Protocol) both server and client side.

**Comment by enisdenjo** [comment]
[Hasura's built in subscriptions solution is `subscriptions-transport-ws`.](https://hasura.io/docs/1.0/graphql/core/subscriptions/index.html#communication-protocol)

As this library offers a fundamentally different Protocol, you cannot use their lib and this one interchangeably.

**Comment by VietKhangLH** [comment]
How can we make it compatible with Hasura ?
Is it a work in Hasura Engine ? (server side)

**Comment by enisdenjo** [comment]
Yap, the [server engine from Hasura](https://github.com/hasura/graphql-engine) has to implement [this Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md). I am most certainly bias, but this Protocol feels more reliable and secure than Apollo's; [I am even pushing it to be a part of the standard together with the brilliant guys from the official GraphQL over HTTP Work Group](https://github.com/graphql/graphql-over-http/pull/140).

I would be happy to push a PR, given enough time; however, their server implementation is written in Haskell which I am not familiar with. 😅

Maybe open a ticket at their repo? See what they think about this?

**Comment by enisdenjo** [comment]
Closing in favour of https://github.com/hasura/graphql-engine/issues/6264.
