### ISSUE TITLE
How client can re-establish connection if server restarts

### ISSUE THREAD

**Issue by kendrickw** [enisdenjo/graphql-ws#81]
When a websocket connection is broken (for example, when server restarts), what is the recommended way for the client to reestablish the websocket connection to the server?

I'm using apollo server, and I get the following error on the client side, whenever the server breaks the ws connection:
```
Object {
  "error": Event {
    "code": 1001,
    "isTrusted": false,
    "reason": "Stream end encountered",
  },
}
```

In the client websocket link, I can see the error:
```
class WebSocketLink extends ApolloLink {
  private client: Client;

  constructor(options: ClientOptions) {
    super();
    this.client = createClient(options);
  }

  public request(operation: Operation): Observable<FetchResult> {
    return new Observable((sink) => {
      return this.client.subscribe<FetchResult>(
        { ...operation, query: print(operation.query) },
        {
          next: sink.next.bind(sink),
          complete: sink.complete.bind(sink),
          error: (err) => {
            switch (err?.code) {
              case 1001:
                // error caught here, but how to reconnect?
                break;
            }
            sink.error(err);
          },
        }
      );
    });
  }
}
```

Currently, I workaround the problem by re-initializing the Apollo Client instance, but I would like to know if there is an official API to restart the socket connection?

**Comment by enisdenjo** [comment]
Hey hey, [the client retries 5 times before finally failing](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/_client_.clientoptions.md#retryattempts) - therefore, it should already be reconnecting on itself.

If thats not the case, please make a repro and I'll fix the bug ASAP.

**Comment by kendrickw** [comment]
In this case, the error object sent by the server is this:
```
Object {
  "error": Event {
    "code": 1001,
    "isTrusted": false,
    "reason": "Stream end encountered",
  },
}
```

In the retry logic: https://github.com/enisdenjo/graphql-ws/blob/5e1fe99c12aaa499a10b5427ce48dab4aea21f37/src/client.ts#L423-L427

It fails the `isCloseEvent` check because `wasClean` is not part of the error object:
https://github.com/enisdenjo/graphql-ws/blob/5e1fe99c12aaa499a10b5427ce48dab4aea21f37/src/client.ts#L600-L602

And thus the retry logic determined that this is not retry-able.

**Comment by enisdenjo** [comment]
Interesting, the close event seems off - [it should have the `wasClean` prop as per the spec](https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent). `isTrusted` is never mentioned there.

Can you share a bit more about your client WebSocket implementation?

**Comment by enisdenjo** [comment]
Found it, that is not a WebSocket native CloseEvent. It seems somehow wrapped in a DOM Event.

[The DOM Event has indeed the `isTrusted` prop.](https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted)

**Comment by kendrickw** [comment]
> Can you share a bit more about your client WebSocket implementation?

I'm using the default WebSocket provided by React Native:
https://reactnative.dev/docs/network#websocket-support

**Comment by enisdenjo** [comment]
Ahh, ok ok. I will investigate how React Native implements WebSocket and adjust the lib accordingly. Thanks for sharing!

**Comment by enisdenjo** [comment]
I've just released a new version which does not care if there is a `wasClean` prop or not. The new, `LikeCloseEvent` requires simply the close `reason` and `code`.

Would be absolutely lovely if you can test it out. 😄

**Comment by kendrickw** [comment]
Works as advertised!
