### ISSUE TITLE
Expected HTTP 101 response but was '400 Bad Request'

### ISSUE THREAD

**Issue by vitorizkiimanda** [enisdenjo/graphql-ws#86]
im following recipes code ( promise ) from https://www.npmjs.com/package/graphql-ws 
![image](https://user-images.githubusercontent.com/28048320/102050321-32a76a80-3e15-11eb-89d9-126f1f8b7034.png)

**Expected Behaviour**
successful handshake with graphql subscription with wss:// protocol

**Actual Behaviour**
got error "Expected HTTP 101 response but was '400 Bad Request'" and "isTrusted:false"
![image](https://user-images.githubusercontent.com/28048320/102050306-29b69900-3e15-11eb-9b43-c86f1b6da5d4.png)

**Debug Information**
already tested using graphiql and it works fine. Got error when implemented in react native 

**Further Information**
just copy paste the example code. nothing change. 
below is my actual code in react native. straight to err ( line-209)
![image](https://user-images.githubusercontent.com/28048320/102050376-4ce14880-3e15-11eb-9b96-93120523878a.png)

![image](https://user-images.githubusercontent.com/28048320/102050408-59fe3780-3e15-11eb-839d-168ab2dfc69e.png)

sorry im a beginner in graphql subscription.

**Comment by enisdenjo** [comment]
Hey hey, seems like the server responds with a different HTTP code instead of accepting a WebSocket handshake. This library cant do that, [it takes in a ready WebSocket connection after the handshake succeeded](https://github.com/enisdenjo/graphql-ws/blob/2aa9c41b79556c061f2354c4157725d6c39b9c67/src/use/ws.ts#L62).

Are you sure you are using `graphql-ws` server side too (not `subscriptions-transport-ws`)? The two libraries are not interchangeable, you must use them coherently - both on the server and client side.

**Comment by vitorizkiimanda** [comment]
> Hey hey, seems like the server responds with a different HTTP code instead of accepting a WebSocket handshake. This library cant do that, [it takes in a ready WebSocket connection after the handshake succeeded](https://github.com/enisdenjo/graphql-ws/blob/2aa9c41b79556c061f2354c4157725d6c39b9c67/src/use/ws.ts#L62).
> 
> Are you sure you are using `graphql-ws` server side too (not `subscriptions-transport-ws`)? The two libraries are not interchangeable, you must use them coherently - both on the server and client side.

well~ seems like our server side is using subcriptions-transport-ws. Let me try it out. Thanks for the advice! appreciate!

**Comment by enisdenjo** [comment]
Glad I could help!

You may use the server recipes from the readme, if your server is implemented in JavaScript - it will just work. If you're using a JS framework which has `subscriptions-transport-ws` built in, would be awesome if you could open an issue on their side (or, if not, I'll be happy to do it). 😄 

But, if your server is implemented in a different language, you have to consult [the GraphQL over WebSocket transport Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md) to implement correct communication with the client.
