### ISSUE TITLE
Couldn't connect from the graphql playground

### ISSUE THREAD

**Issue by skk2142** [enisdenjo/graphql-ws#88]
**Screenshot**
<img width="1792" alt="Screen Shot 2020-12-21 at 12 14 46 PM" src="https://user-images.githubusercontent.com/10248760/102803630-86223700-4386-11eb-9828-42709147063a.png">

**Expected Behaviour**
I should be able to create a subscription on the client (playground). I'm using Apollo Server. 

**Actual Behaviour**
Graphql queries are working but subscription is not. 

**Debug Information**
```javascript
import { useServer } from 'graphql-ws/lib/use/ws';
import { execute, subscribe } from 'graphql';
import ws from 'ws';


const mockChatServer = new ApolloServer({
  schema: mockSchema,
});

const app = express();
app.use(bodyParser.json());
mockChatServer.applyMiddleware({ app });

const server = createServer(app);
const wsServer = new ws.Server({
  server,
  path: '/graphql',
});

server.listen(3002, () => {
  useServer(
    {
      execute,
      subscribe,
      roots: chatResolvers,
      schema: mockSchema,
      onConnect: ctx => {
        console.log('onconnect');
        return true;
      },
      context: {
        name: 'cool',
      },
      onSubscribe: () => {
        console.log('onsubscribe');
      },
    },
    wsServer,
  );
});


```

**Further Information**
None of the console logs about are being called. This is my first time trying to use graphql subscription so I might be making a silly mistake. The subscription endpoint (/graphql) is same as graphql query endpoint but that should not be a problem. 
Thank you so much for writing this library. It'd be great if there was a working example.

**Comment by maxpain** [comment]
@skk2142 seems like graphql-playground uses old `subscriptions-transport-ws` subprotocol

**Comment by skk2142** [comment]
Thanks. I'm using [Express Playground](https://www.npmjs.com/package/graphql-playground-middleware-express) now and I don't get that connection error. However, the websocket connection seems to be still not created. There is a 'Listening...' message in the playground though. Also, I don't get any logs from the `onConnect` and `onSubscribe` callbacks. Here's another screenshot:
<img width="1792" alt="Screen Shot 2020-12-21 at 1 02 13 PM" src="https://user-images.githubusercontent.com/10248760/102807511-c8e70d80-438c-11eb-9583-61f155eb0bf3.png">

**Comment by enisdenjo** [comment]
As @maxpain mentioned, the server and the client must both implement [this Protocol](https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md). In your case the [Express Playground client is using `subscriptions-transport-ws`](https://github.com/graphql/graphql-playground/blob/36a7e70cc43cb3a613586cf9e8be47ab10de0191/packages/graphql-playground-react/package.json#L160) instead of this lib.

Consider opening an Issue over at [`graphql-playground`](https://github.com/graphql/graphql-playground).

**Comment by enisdenjo** [comment]
Closing due to irrelevance and inactivity.
