### ISSUE TITLE
Server onDisconnect event

### ISSUE THREAD

**Issue by MartijnHols** [enisdenjo/graphql-ws#91]
### Story

As a server I want to track the amount of open websocket connections and update the user's online status when a user disconnects so that I can monitor and analyze the health of my server and update a user's online status immediately when the browser is closed.

### Acceptance criteria

- server can add a disconnect event listener
- server's disconnect event listener passes either the connection's context or the ctx's extra with request to be able to determine the user

### Example use case

```
import client from 'prom-client'

const webSocketTotalConnectionsCounter = new client.Counter({
  name: 'websocket_connections_total',
  help: 'The total number of Apollo WebSocket connections handled so far.',
})
const webSocketOpenConnectionsGauge = new client.Gauge({
  name: 'websocket_connections_open',
  help: 'The number of open Apollo WebSocket connections.',
})

useServer(
  {
    schema,
    execute,
    subscribe,
    async onConnect(ctx) {
      webSocketTotalConnectionsCounter.inc()
      webSocketOpenConnectionsGauge.inc()

      await setOnline(ctx)
    },
    async onDisconnect(ctx) {
      webSocketOpenConnectionsGauge.dec()

      await setOffline(ctx)
    },
  },
  wsServer,
)
```

**Comment by brettjashford** [comment]
i have yet to switch from `subscriptions-transport-ws`, but an `onDisconnect` server callback would be helpful. currently use this to send stats to datadog on the number of connected clients

**Comment by enisdenjo** [comment]
The thing is, [the actual "server" is just a connection controller which can be hooked up to any WebSocket implementation](https://github.com/enisdenjo/graphql-ws/blob/master/src/server.ts). Its meant to be ultra minimal and its sole purpose is marshalling the messages and having high level control over the channel. Because of this, it does not have a concept of "disconnect" - it simply does not care. So, ultimately, there is no place for a `onDisconnect` in the controller.

However, you can indeed achieve this right now by hooking up on the `onclose` event in the `ws.Server` instance or by creating your custom implementation over `ws` using the raw `import { makeServer } from 'graphql-ws'`. You can check how I implement `ws` here:
https://github.com/enisdenjo/graphql-ws/blob/5483face7d6538f00aced765adf11245e07ad393/src/use/ws.ts#L25-L126

If you need additional help, I'll write up an usage example for you!

**Comment by enisdenjo** [comment]
I spoke too soon... PR coming soon!

**Comment by enisdenjo** [comment]
Hey @MartijnHols and @brettjashford, I've added 2 new callbacks: `onDisconnect` and `onClose`. Both are used for tracking socket closures; however, they are a bit different:

#### [`onDisconnect`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.serveroptions.md#ondisconnect)
Called exclusively after the connection has been acknowledged (the client successfully went through the connection initialisation phase). Meaning, you can chain the `onConnect` + `onDisconnect` to track actual, compatible, clients. `onConnect` will **always** be called before `onDisconnect`.

#### [`onClose`](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.serveroptions.md#onclose)
Called when the socket closes at any point in time. It does not care if the connection has been acknowledge. The `onConnect` callback must not necessarily be called before it.

**Comment by acro5piano** [comment]
Hi @enisdenjo thank you for the amazing library!

I would like to implement the same feature of what @MartijnHols said.

> update the user's online status when a user disconnects

The code should be like this, right?

```ts
useServer({
  context: (ctx) => ({
    userId: ctx.connectionParams.userId // psuedo code, no auth logic
  }),
  onDisconnect: (ctx) => {
    db.update({ status: 'offline' }).where({ userId: ctx.connectionParams.userId })
  }
}, ws )
```

**Comment by enisdenjo** [comment]
Hey there @acro5piano! I'd recommend reading https://github.com/enisdenjo/graphql-ws/issues/91#issuecomment-759363519 to understand the difference between `onClose` and `onDisconnect`.

In essence, `onDisconnect` is called only if the user successfully went through the connection phase (WebSocket established + `ConnectionAck` message dispatched). On the other hand, `onClose` is called regardless if the user successfully connected or not - so, every time the socket closes. The  call order when the WebSocket closes is:
1. `if acknowledged then onDisconnect`
1. `onClose`

**Comment by acro5piano** [comment]
@enisdenjo 
Thank you for your quick response! So `onClose` seems better because it is possible that user disconnects without sending signals, e.g.) internet disconnection.

**Comment by enisdenjo** [comment]
If the user disconnects abruptly without `graphql-ws` acknowledging the connection, only `onClose` will be called. So, yeah, I'd suggest using `onClose` in your case.

**Comment by acro5piano** [comment]
@enisdenjo Thanks for your help!
