### ISSUE TITLE
missing exports in browser bundle 

### ISSUE THREAD

**Issue by michelepra** [enisdenjo/graphql-ws#97]
UMD file has missing exports that is declared in *d.ts file

When using module bundler for browser like [webpack with web target](https://webpack.js.org/configuration/target/) that honor https://github.com/enisdenjo/graphql-ws/blob/3f5c42e3deb7d014258417d20df29ef9e1fb1ed7/package.json#L25
resulting bundle cannot be execute if using exported code other than [createClient method](https://github.com/enisdenjo/graphql-ws/blob/792b4736f85be383cb68ffe14a2402d05dcb20d2/src/client.ts#L173)

For example using enum [MessageType](https://github.com/enisdenjo/graphql-ws/blob/792b4736f85be383cb68ffe14a2402d05dcb20d2/src/client.ts#L11) in application code, the bundle resulting buggy in runtime due to missing exported MessageType in graphql-ws umd

To fix just re-export in client.ts or change [entry point for rollup](https://github.com/enisdenjo/graphql-ws/blob/792b4736f85be383cb68ffe14a2402d05dcb20d2/rollup.config.js#L5) from `./src/client.ts` to `./src/index.ts`

**Comment by enisdenjo** [comment]
Hey hey, thanks for bringing this up! A PR is incoming.
