### ISSUE TITLE
Allow client timeout to be specified by the user so it can be set to a higher value than 5 seconds

### ISSUE THREAD

**Issue by Kingdutch** [enisdenjo/graphql-ws#98]
### Story

As a user I'm sometimes opening subscriptions to servers that may need to authenticate some form of credentials which could be dependant on other services

I want to be able to specify a longer timeout before the connection is closed while waiting for the ConnectionAck method

So that I don't fail to connect when authentication to the server takes longer.

### Acceptance criteria

- client is able to set the connection timeout during client creation

**Comment by enisdenjo** [comment]
You can indeed do that already, but on the server side since clients can't (and should not) make that decision. [Check out the `connectionInitWaitTimeout` server option.](https://github.com/enisdenjo/graphql-ws/blob/master/docs/interfaces/server.serveroptions.md#connectioninitwaittimeout)

**Comment by Kingdutch** [comment]
The client is making such a decision though, putting the server on the clock. See https://github.com/enisdenjo/graphql-ws/blob/51e54591ab4f9a9c9ac4a903e81318b6f1c7860f/src/client.ts#L359 

In my case I'm using the PHP WebSocket Server implementation: https://github.com/goalgorilla/graphql-php-ws The client is sending the init message quickly enough. However, the server needs to go to an external service that often takes about 6 seconds to come back with a reply. This means that the client terminates the connection just as the server is ready to acknowledge the connection.

I can not acknowledge the connection sooner because the client is unauthenticated, so acknowledging the connection during the authentication would incorrectly signal to the client that they're ready to start subscriptions (because unauthenticated subscriptions are invalid in the application).

**Comment by enisdenjo** [comment]
Ahh, yes! You are absolutely right. Even though, thats not a `ConnectionInit` waiter, it was actually thought of as safeguard that prevents never-ending promises. But, I think we dont even need it...

Anyways, thanks for clarifying and brining it up! A PR coming very soon.

**Comment by enisdenjo** [comment]
Oh and, awesome work with the PHP WS server! Lovely to see other people implementing the Protocol in various languages. 😄

**Comment by Kingdutch** [comment]
Awesome stuff! Thanks!
