### ISSUE TITLE
Subscriptions aren't re-submitted properly on reconnection

### ISSUE THREAD

**Issue by michelepra** [enisdenjo/graphql-ws#99]
like #85 i have same behavior

i see this happend when websocket stay in CONNECTING state more than 2750ms

[Connect function](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L291) when websocket state is CONNECTING [call itself](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L337) 

This cycle is limited to [10 times to prevent many recursive calls](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L297) and at every call wait for [50*callDepth](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L301) ms

So if websocket state is CONNECTING for more than 2750ms connect thow [this error](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L298)
![image](https://user-images.githubusercontent.com/11311941/105197900-658ffd00-5b3d-11eb-9f3a-fa74b5570798.png)

![image](https://user-images.githubusercontent.com/11311941/105200863-8d349480-5b40-11eb-861a-e7a65e0ed762.png)

Subscription promise [catch this error](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L655) so this mean that [subscription message](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L623) never send when websocket state switch to CONNECTED

I also note that if sync object is wrapped with observable library like rxjs [error throw here](https://github.com/enisdenjo/graphql-ws/blob/4951e43cc1eebc4e1c90a265701a29236277f2cf/src/client.ts#L298) will call unsubscribe that definetly stop subscription life

```
import { Observable } from 'rxjs'
import { Client, SubscribePayload } from 'graphql-ws'
function subscribe(client: Client, gql: SubscribePayload) {
  return new Observable(subscriber => {
    const unsubscribe = client.subscribe(gql, {
      next: subscriber.next.bind(subscriber),
      error: subscriber.error.bind(subscriber),
      complete: subscriber.complete.bind(subscriber),
    })
    return () => unsubscribe()
  })
}
```

**Comment by enisdenjo** [comment]
Thank you for the elaborate explanation! I have some ideas in mind that can potentially fix this behaviour, PR coming in soon.

**Comment by momakes2** [comment]
Thank you @michelepra @enisdenjo!

**Comment by enisdenjo** [comment]
Hey @michelepra, @momakes2, I've done a rewrite of the client internals in #100. Would be great if you guys could try out the [`v4.1.2` release](https://github.com/enisdenjo/graphql-ws/releases/tag/v4.1.2) and check if this issue is still present.

**Comment by michelepra** [comment]
Now it seem ok!! Great work... Many thanks

**Comment by enisdenjo** [comment]
🚀 Awesome to hear that! Yes, your analysis helped a lot, thank you once again. 😄
